/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nutrii.application.gui;

import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JTextField;

/**
 *
 * @author Blakey
 */
public class CreateMeal extends javax.swing.JPanel {

    /**
     * Creates new form MngDietPnl1
     */
    public CreateMeal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MDP1 = new javax.swing.JPanel();
        MDP1DayConsumedListLbl = new javax.swing.JLabel();
        addFoodBtn = new javax.swing.JButton();
        addDrinkBtn = new javax.swing.JButton();
        foodCmb = new javax.swing.JComboBox<>();
        drinkCmb = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        mealList = new javax.swing.JList<>();
        confirmBtn = new javax.swing.JButton();
        mealNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        CreateNewDayTitleLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(15, 93, 70));

        MDP1.setBackground(new java.awt.Color(15, 93, 70));

        MDP1DayConsumedListLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MDP1DayConsumedListLbl.setForeground(new java.awt.Color(255, 255, 255));
        MDP1DayConsumedListLbl.setText("Food List:");

        addFoodBtn.setBackground(new java.awt.Color(10, 36, 2));
        addFoodBtn.setForeground(new java.awt.Color(255, 255, 255));
        addFoodBtn.setText("Add Food");
        addFoodBtn.setBorder(null);
        addFoodBtn.setBorderPainted(false);
        addFoodBtn.setFocusPainted(false);
        addFoodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFoodBtnActionPerformed(evt);
            }
        });

        addDrinkBtn.setBackground(new java.awt.Color(10, 36, 2));
        addDrinkBtn.setForeground(new java.awt.Color(255, 255, 255));
        addDrinkBtn.setText("Add Drink");
        addDrinkBtn.setBorder(null);
        addDrinkBtn.setBorderPainted(false);
        addDrinkBtn.setFocusPainted(false);
        addDrinkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDrinkBtnActionPerformed(evt);
            }
        });

        foodCmb.setBorder(null);

        drinkCmb.setBorder(null);

        mealList.setBorder(null);
        mealList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mealList.setFixedCellHeight(30);
        mealList.setSelectionBackground(new java.awt.Color(15, 93, 70));
        mealList.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(mealList);

        confirmBtn.setBackground(new java.awt.Color(10, 36, 2));
        confirmBtn.setForeground(new java.awt.Color(255, 255, 255));
        confirmBtn.setText("Confirm Meal");
        confirmBtn.setBorder(null);
        confirmBtn.setBorderPainted(false);
        confirmBtn.setFocusPainted(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Meal Name:");

        javax.swing.GroupLayout MDP1Layout = new javax.swing.GroupLayout(MDP1);
        MDP1.setLayout(MDP1Layout);
        MDP1Layout.setHorizontalGroup(
            MDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MDP1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MDP1DayConsumedListLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MDP1Layout.createSequentialGroup()
                        .addGroup(MDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MDP1Layout.createSequentialGroup()
                                .addComponent(addFoodBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addDrinkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MDP1Layout.createSequentialGroup()
                                .addComponent(foodCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(drinkCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46)
                        .addGroup(MDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mealNameField)
                            .addGroup(MDP1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(MDP1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(MDP1Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MDP1Layout.setVerticalGroup(
            MDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MDP1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(MDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drinkCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFoodBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDrinkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mealNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(MDP1DayConsumedListLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        CreateNewDayTitleLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CreateNewDayTitleLbl.setForeground(new java.awt.Color(255, 255, 255));
        CreateNewDayTitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CreateNewDayTitleLbl.setText("Create New Meal");

        backBtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("< Back");
        backBtn.setBorder(null);
        backBtn.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CreateNewDayTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(CreateNewDayTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MDP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MDP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addFoodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFoodBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addFoodBtnActionPerformed

    private void addDrinkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDrinkBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addDrinkBtnActionPerformed

    public void setComboBoxValues(DefaultComboBoxModel foodmodel, DefaultComboBoxModel drinkmodel) {
        foodCmb.setModel(foodmodel);
        drinkCmb.setModel(drinkmodel);
    }

    public void addFoodListener(ActionListener a) {
        addFoodBtn.addActionListener(a);

    }

    public JButton getAddDrinkBtn() {
        return addDrinkBtn;
    }

    public JButton getAddFoodBtn() {
        return addFoodBtn;
    }

    public JList<String> getMealList() {
        return mealList;
    }

    public void addDrinkListener(ActionListener a) {
        addDrinkBtn.addActionListener(a);
    }

    public JComboBox<String> getDrinkCmb() {
        return drinkCmb;
    }

    public void addConfirmListener(ActionListener a){
        confirmBtn.addActionListener(a);
    }
  
    public JComboBox<String> getFoodCmb() {
        return foodCmb;
    }

    public JTextField getMealNameField() {
        return mealNameField;
    }
    
    public void addBackBtnListener(ActionListener a){
        backBtn.addActionListener(a);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CreateNewDayTitleLbl;
    private javax.swing.JPanel MDP1;
    private javax.swing.JLabel MDP1DayConsumedListLbl;
    private javax.swing.JButton addDrinkBtn;
    private javax.swing.JButton addFoodBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JComboBox<String> drinkCmb;
    private javax.swing.JComboBox<String> foodCmb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> mealList;
    private javax.swing.JTextField mealNameField;
    // End of variables declaration//GEN-END:variables

    public JButton getConfirmBtn() {
        return confirmBtn;
    }
}
