/*

 * and open the template in the editor.
 */
package nutrii.application.gui;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Blakey
 */
public class MenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form MenuPanel
     */
    int xMouse;
    int yMouse;
    
    
    public MenuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        closeBtn = new javax.swing.JLabel();
        minimiseBtn = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        menuContainer = new javax.swing.JPanel();
        AddConsumedPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        ManageItemsPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        UseFoodCalculatorPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        ManageDietPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        headerLabel = new javax.swing.JLabel();

        jButton6.setBackground(new java.awt.Color(100, 137, 108));
        jButton6.setForeground(new java.awt.Color(204, 204, 204));
        jButton6.setText("jButton1");

        jButton8.setBackground(new java.awt.Color(100, 137, 108));
        jButton8.setForeground(new java.awt.Color(204, 204, 204));
        jButton8.setText("jButton1");

        jButton10.setBackground(new java.awt.Color(100, 137, 108));
        jButton10.setForeground(new java.awt.Color(204, 204, 204));
        jButton10.setText("jButton1");

        setBackground(new java.awt.Color(102, 102, 102));
        setMinimumSize(new java.awt.Dimension(640, 620));
        setOpaque(false);
        setLayout(null);

        header.setOpaque(false);
        header.setPreferredSize(new java.awt.Dimension(120, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("NUTRII");

        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeBtnMousePressed(evt);
            }
        });

        minimiseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minimiseBtnMousePressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nutrii/application/gui/images/user.png"))); // NOI18N

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addGap(241, 241, 241)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addComponent(minimiseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(closeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(minimiseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(header);
        header.setBounds(0, 0, 790, 80);

        container.setOpaque(false);
        container.setLayout(new java.awt.BorderLayout());

        menuContainer.setBackground(new java.awt.Color(14, 81, 25));
        menuContainer.setOpaque(false);
        menuContainer.setLayout(new java.awt.GridLayout(2, 2, 1, 0));

        AddConsumedPanel.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add Item to Record");

        jButton4.setBackground(new java.awt.Color(100, 137, 108));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Add new Food item or Drink item");

        javax.swing.GroupLayout AddConsumedPanelLayout = new javax.swing.GroupLayout(AddConsumedPanel);
        AddConsumedPanel.setLayout(AddConsumedPanelLayout);
        AddConsumedPanelLayout.setHorizontalGroup(
            AddConsumedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddConsumedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddConsumedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
                .addContainerGap())
        );
        AddConsumedPanelLayout.setVerticalGroup(
            AddConsumedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddConsumedPanelLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        menuContainer.add(AddConsumedPanel);

        ManageItemsPanel.setOpaque(false);
        ManageItemsPanel.setPreferredSize(new java.awt.Dimension(124, 186));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Remove Item From Record");

        jButton11.setBackground(new java.awt.Color(100, 137, 108));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Remove Item from Record");

        javax.swing.GroupLayout ManageItemsPanelLayout = new javax.swing.GroupLayout(ManageItemsPanel);
        ManageItemsPanel.setLayout(ManageItemsPanelLayout);
        ManageItemsPanelLayout.setHorizontalGroup(
            ManageItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageItemsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ManageItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
                .addContainerGap())
        );
        ManageItemsPanelLayout.setVerticalGroup(
            ManageItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageItemsPanelLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        menuContainer.add(ManageItemsPanel);

        UseFoodCalculatorPanel.setOpaque(false);
        UseFoodCalculatorPanel.setPreferredSize(new java.awt.Dimension(124, 186));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Use Food Calculator");

        jButton9.setBackground(new java.awt.Color(100, 137, 108));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Food Calculator");

        javax.swing.GroupLayout UseFoodCalculatorPanelLayout = new javax.swing.GroupLayout(UseFoodCalculatorPanel);
        UseFoodCalculatorPanel.setLayout(UseFoodCalculatorPanelLayout);
        UseFoodCalculatorPanelLayout.setHorizontalGroup(
            UseFoodCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UseFoodCalculatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UseFoodCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        UseFoodCalculatorPanelLayout.setVerticalGroup(
            UseFoodCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UseFoodCalculatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        menuContainer.add(UseFoodCalculatorPanel);

        ManageDietPanel.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Diet");

        jButton1.setBackground(new java.awt.Color(100, 137, 108));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Create new Day");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton2.setBackground(new java.awt.Color(100, 137, 108));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("View Days");

        jButton3.setBackground(new java.awt.Color(100, 137, 108));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Adjust Days");

        javax.swing.GroupLayout ManageDietPanelLayout = new javax.swing.GroupLayout(ManageDietPanel);
        ManageDietPanel.setLayout(ManageDietPanelLayout);
        ManageDietPanelLayout.setHorizontalGroup(
            ManageDietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageDietPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(ManageDietPanelLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(ManageDietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ManageDietPanelLayout.setVerticalGroup(
            ManageDietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageDietPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        menuContainer.add(ManageDietPanel);

        container.add(menuContainer, java.awt.BorderLayout.CENTER);

        add(container);
        container.setBounds(2, 76, 790, 720);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nutrii/application/gui/images/bgNutrii.jpg"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(-4, -30, 860, 860);

        headerLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerLabelMouseDragged(evt);
            }
        });
        headerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerLabelMousePressed(evt);
            }
        });
        add(headerLabel);
        headerLabel.setBounds(0, 0, 598, 75);
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMousePressed
        System.exit(0);
    }//GEN-LAST:event_closeBtnMousePressed

    private void minimiseBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimiseBtnMousePressed
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        parentFrame.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimiseBtnMousePressed

    private void headerLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerLabelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerLabelMousePressed

    private void headerLabelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerLabelMouseDragged
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        parentFrame.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerLabelMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddConsumedPanel;
    private javax.swing.JPanel ManageDietPanel;
    private javax.swing.JPanel ManageItemsPanel;
    private javax.swing.JPanel UseFoodCalculatorPanel;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JPanel container;
    private javax.swing.JPanel header;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel menuContainer;
    private javax.swing.JLabel minimiseBtn;
    // End of variables declaration//GEN-END:variables
}
