/*

 * and open the template in the editor.
 */
package nutrii.application.gui;

import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Blakey
 */
public class MenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form MenuPanel
     */
    int xMouse;
    int yMouse;
    boolean isOptionsVisible = false;

    public MenuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        userOptions = new javax.swing.JPanel();
        userOptions.setVisible(false);
        accountBtn = new javax.swing.JButton();
        usersBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        userMenu = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        closeBtn = new javax.swing.JLabel();
        minimiseBtn = new javax.swing.JLabel();
        userNameLbl = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        menuContainer = new javax.swing.JPanel();
        AddConsumedPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        addFoodItemBtn = new javax.swing.JButton();
        ManageItemsPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        removeFoodItemBtn = new javax.swing.JButton();
        UseFoodCalculatorPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        ManageDietPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        headerLabel = new javax.swing.JLabel();

        jButton6.setBackground(new java.awt.Color(100, 137, 108));
        jButton6.setForeground(new java.awt.Color(204, 204, 204));
        jButton6.setText("jButton1");

        jButton8.setBackground(new java.awt.Color(100, 137, 108));
        jButton8.setForeground(new java.awt.Color(204, 204, 204));
        jButton8.setText("jButton1");

        jButton10.setBackground(new java.awt.Color(100, 137, 108));
        jButton10.setForeground(new java.awt.Color(204, 204, 204));
        jButton10.setText("jButton1");

        setBackground(new java.awt.Color(102, 102, 102));
        setMinimumSize(new java.awt.Dimension(640, 620));
        setOpaque(false);
        setLayout(null);

        userOptions.setEnabled(false);
        userOptions.setFocusable(false);
        userOptions.setOpaque(false);
        userOptions.setLayout(new java.awt.GridLayout(3, 0));

        accountBtn.setBackground(new java.awt.Color(10, 36, 2));
        accountBtn.setForeground(new java.awt.Color(255, 255, 255));
        accountBtn.setText("ACCOUNT");
        accountBtn.setBorderPainted(false);
        accountBtn.setContentAreaFilled(false);
        accountBtn.setFocusPainted(false);
        accountBtn.setOpaque(true);
        userOptions.add(accountBtn);

        usersBtn.setBackground(new java.awt.Color(10, 36, 2));
        usersBtn.setForeground(new java.awt.Color(255, 255, 255));
        usersBtn.setText("USERS");
        usersBtn.setBorderPainted(false);
        usersBtn.setContentAreaFilled(false);
        usersBtn.setFocusPainted(false);
        usersBtn.setOpaque(true);
        userOptions.add(usersBtn);

        logOutBtn.setBackground(new java.awt.Color(10, 36, 2));
        logOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logOutBtn.setText("LOG OUT");
        logOutBtn.setBorderPainted(false);
        logOutBtn.setContentAreaFilled(false);
        logOutBtn.setFocusPainted(false);
        logOutBtn.setOpaque(true);
        userOptions.add(logOutBtn);

        add(userOptions);
        userOptions.setBounds(0, 80, 220, 250);

        header.setOpaque(false);
        header.setPreferredSize(new java.awt.Dimension(120, 50));

        userMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nutrii/application/gui/images/user.png"))); // NOI18N
        userMenu.setToolTipText("User Settings");
        userMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMenuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userMenuMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("NUTRII");

        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeBtnMousePressed(evt);
            }
        });

        minimiseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minimiseBtnMousePressed(evt);
            }
        });

        userNameLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userNameLbl.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(minimiseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(closeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(minimiseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        add(header);
        header.setBounds(0, 0, 790, 80);

        container.setOpaque(false);
        container.setLayout(new java.awt.BorderLayout());

        menuContainer.setBackground(new java.awt.Color(14, 81, 25));
        menuContainer.setOpaque(false);
        menuContainer.setLayout(new java.awt.GridLayout(2, 2, 1, 0));

        AddConsumedPanel.setOpaque(false);
        AddConsumedPanel.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add Item to Record");
        AddConsumedPanel.add(jLabel3);
        jLabel3.setBounds(0, 70, 382, 30);

        addFoodItemBtn.setBackground(new java.awt.Color(2, 58, 15));
        addFoodItemBtn.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        addFoodItemBtn.setForeground(new java.awt.Color(255, 255, 255));
        addFoodItemBtn.setText("Add new Food or Drink ");
        addFoodItemBtn.setBorderPainted(false);
        addFoodItemBtn.setContentAreaFilled(false);
        AddConsumedPanel.add(addFoodItemBtn);
        addFoodItemBtn.setBounds(22, 110, 370, 183);

        menuContainer.add(AddConsumedPanel);

        ManageItemsPanel.setOpaque(false);
        ManageItemsPanel.setPreferredSize(new java.awt.Dimension(124, 186));
        ManageItemsPanel.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Remove Item From Record");
        ManageItemsPanel.add(jLabel4);
        jLabel4.setBounds(6, 63, 382, 30);

        removeFoodItemBtn.setBackground(new java.awt.Color(100, 137, 108));
        removeFoodItemBtn.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        removeFoodItemBtn.setForeground(new java.awt.Color(255, 255, 255));
        removeFoodItemBtn.setText("Remove Item from Record");
        removeFoodItemBtn.setBorderPainted(false);
        removeFoodItemBtn.setContentAreaFilled(false);
        ManageItemsPanel.add(removeFoodItemBtn);
        removeFoodItemBtn.setBounds(10, 110, 370, 183);

        menuContainer.add(ManageItemsPanel);

        UseFoodCalculatorPanel.setOpaque(false);
        UseFoodCalculatorPanel.setPreferredSize(new java.awt.Dimension(124, 186));
        UseFoodCalculatorPanel.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Use Food Calculator");
        UseFoodCalculatorPanel.add(jLabel2);
        jLabel2.setBounds(10, 0, 369, 30);

        jButton9.setBackground(new java.awt.Color(100, 137, 108));
        jButton9.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Food Calculator");
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setDefaultCapable(false);
        UseFoodCalculatorPanel.add(jButton9);
        jButton9.setBounds(20, 70, 370, 190);

        menuContainer.add(UseFoodCalculatorPanel);

        ManageDietPanel.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Diet");

        jButton1.setBackground(new java.awt.Color(100, 137, 108));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Create new Day");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton2.setBackground(new java.awt.Color(100, 137, 108));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("View Days");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);

        jButton3.setBackground(new java.awt.Color(100, 137, 108));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Adjust Days");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);

        javax.swing.GroupLayout ManageDietPanelLayout = new javax.swing.GroupLayout(ManageDietPanel);
        ManageDietPanel.setLayout(ManageDietPanelLayout);
        ManageDietPanelLayout.setHorizontalGroup(
            ManageDietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageDietPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(ManageDietPanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(ManageDietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ManageDietPanelLayout.setVerticalGroup(
            ManageDietPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageDietPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        menuContainer.add(ManageDietPanel);

        container.add(menuContainer, java.awt.BorderLayout.CENTER);

        add(container);
        container.setBounds(2, 76, 790, 720);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nutrii/application/gui/images/bgNutri2i.jpg"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(-4, -30, 860, 860);

        headerLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerLabelMouseDragged(evt);
            }
        });
        headerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerLabelMousePressed(evt);
            }
        });
        add(headerLabel);
        headerLabel.setBounds(0, 0, 598, 75);
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMousePressed
        System.exit(0);
    }//GEN-LAST:event_closeBtnMousePressed

    private void minimiseBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimiseBtnMousePressed
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        parentFrame.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimiseBtnMousePressed

    private void headerLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerLabelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerLabelMousePressed

    private void headerLabelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerLabelMouseDragged
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        parentFrame.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerLabelMouseDragged

    private void userMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMenuMousePressed
        // TODO add your handling code here:
        if (!isOptionsVisible) {
            showUserMenu();
            System.out.println(isOptionsVisible);
        } else {
            hideUserMenu();
            System.out.println(isOptionsVisible);
        }

    }//GEN-LAST:event_userMenuMousePressed

    public void adduserLabelListener(ActionListener a, String text) {
        userNameLbl.setText(text);
    }

    public void viewAccntListener(ActionListener a) {
        accountBtn.addActionListener(a);
    }

    //toggle user menu visibility
    private void userMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMenuMouseClicked
        if (!isOptionsVisible) {
            isOptionsVisible = true;
        } else {
            isOptionsVisible = false;
        }
    }//GEN-LAST:event_userMenuMouseClicked

    public void addLogOutListener(ActionListener a) {
        logOutBtn.addActionListener(a);
    }

    public void addFoodItemListener(ActionListener a) {
        addFoodItemBtn.addActionListener(a);
    }

    public void removeFoodItemListener(ActionListener a) {
        removeFoodItemBtn.addActionListener(a);
    }

    private void showUserMenu() {
        userOptions.setVisible(true);
    }

    private void hideUserMenu() {
        userOptions.setVisible(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddConsumedPanel;
    private javax.swing.JPanel ManageDietPanel;
    private javax.swing.JPanel ManageItemsPanel;
    private javax.swing.JPanel UseFoodCalculatorPanel;
    private javax.swing.JButton accountBtn;
    private javax.swing.JButton addFoodItemBtn;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JPanel container;
    private javax.swing.JPanel header;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JPanel menuContainer;
    private javax.swing.JLabel minimiseBtn;
    private javax.swing.JButton removeFoodItemBtn;
    private javax.swing.JLabel userMenu;
    private javax.swing.JLabel userNameLbl;
    private javax.swing.JPanel userOptions;
    private javax.swing.JButton usersBtn;
    // End of variables declaration//GEN-END:variables
}
