/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nutrii.application.gui;

/**
 *
 * @author Blakey
 */
public class MngDietPnl1 extends javax.swing.JPanel {

/**
 * Creates new form MngDietPnl1
 */
public MngDietPnl1() {
    initComponents();
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CreateNewDayTitleLbl = new javax.swing.JLabel();
        MDP1 = new javax.swing.JPanel();
        MDP1SelectDayLbl = new javax.swing.JLabel();
        MDP1DayLbl = new javax.swing.JLabel();
        MDP1MonthLbl = new javax.swing.JLabel();
        MDP1YearLbl = new javax.swing.JLabel();
        MDP1DayTxtField = new javax.swing.JTextField();
        MDP1MonthTxtField = new javax.swing.JTextField();
        MDP1YearTxtField = new javax.swing.JTextField();
        AddToDayConsumedTitleLbl = new javax.swing.JLabel();
        MDP1CreateDayRecordBtn = new javax.swing.JButton();
        MDP1DayConsumedListLbl = new javax.swing.JLabel();
        MDP1AddMealBtn = new javax.swing.JButton();
        MDP1AddFoodBtn = new javax.swing.JButton();
        MDP1AddDrinkBtn = new javax.swing.JButton();
        MDP1AddMealComboBox = new javax.swing.JComboBox<>();
        MDP1AddFoodComboBox = new javax.swing.JComboBox<>();
        MDP1AddDrinkComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        MDP1DayConsumedListOutput = new javax.swing.JTextArea();
        MDP1DayNotif = new javax.swing.JLabel();

        CreateNewDayTitleLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CreateNewDayTitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CreateNewDayTitleLbl.setText("Create New Day");

        MDP1.setBackground(new java.awt.Color(153, 153, 153));

        MDP1SelectDayLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MDP1SelectDayLbl.setForeground(new java.awt.Color(51, 51, 51));
        MDP1SelectDayLbl.setText("Select Day");

        MDP1DayLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MDP1DayLbl.setForeground(new java.awt.Color(102, 102, 102));
        MDP1DayLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MDP1DayLbl.setText("DD");

        MDP1MonthLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MDP1MonthLbl.setForeground(new java.awt.Color(102, 102, 102));
        MDP1MonthLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MDP1MonthLbl.setText("MM");

        MDP1YearLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MDP1YearLbl.setForeground(new java.awt.Color(102, 102, 102));
        MDP1YearLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MDP1YearLbl.setText("YYYY");

        MDP1DayTxtField.setText("01");
        MDP1DayTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MDP1DayTxtFieldActionPerformed(evt);
            }
        });

        MDP1MonthTxtField.setText("01");
        MDP1MonthTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MDP1MonthTxtFieldActionPerformed(evt);
            }
        });

        MDP1YearTxtField.setText("2020");
        MDP1YearTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MDP1YearTxtFieldActionPerformed(evt);
            }
        });

        AddToDayConsumedTitleLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddToDayConsumedTitleLbl.setForeground(new java.awt.Color(51, 51, 51));
        AddToDayConsumedTitleLbl.setText("Add to Day Consumed List:");

        MDP1CreateDayRecordBtn.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        MDP1CreateDayRecordBtn.setText("Create Day Record");
        MDP1CreateDayRecordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MDP1CreateDayRecordBtnActionPerformed(evt);
            }
        });

        MDP1DayConsumedListLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MDP1DayConsumedListLbl.setForeground(new java.awt.Color(51, 51, 51));
        MDP1DayConsumedListLbl.setText("Day Consumed List:");

        MDP1AddMealBtn.setText("Add Meal");

        MDP1AddFoodBtn.setText("Add Food");
        MDP1AddFoodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MDP1AddFoodBtnActionPerformed(evt);
            }
        });

        MDP1AddDrinkBtn.setText("Add Drink");
        MDP1AddDrinkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MDP1AddDrinkBtnActionPerformed(evt);
            }
        });

        MDP1AddMealComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        MDP1AddFoodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        MDP1AddDrinkComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        MDP1DayConsumedListOutput.setColumns(20);
        MDP1DayConsumedListOutput.setRows(5);
        MDP1DayConsumedListOutput.setText("Empty");
        jScrollPane1.setViewportView(MDP1DayConsumedListOutput);

        MDP1DayNotif.setText("That Day Already exists~");

        javax.swing.GroupLayout MDP1Layout = new javax.swing.GroupLayout(MDP1);
        MDP1.setLayout(MDP1Layout);
        MDP1Layout.setHorizontalGroup(
            MDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MDP1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MDP1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(MDP1CreateDayRecordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MDP1DayNotif, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(MDP1SelectDayLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MDP1DayConsumedListLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                    .addGroup(MDP1Layout.createSequentialGroup()
                        .addGroup(MDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MDP1Layout.createSequentialGroup()
                                .addComponent(MDP1AddMealComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MDP1AddFoodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MDP1AddDrinkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MDP1Layout.createSequentialGroup()
                                .addComponent(MDP1AddMealBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MDP1AddFoodBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MDP1AddDrinkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(MDP1Layout.createSequentialGroup()
                        .addGroup(MDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(MDP1Layout.createSequentialGroup()
                                .addGroup(MDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(MDP1DayTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MDP1DayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(MDP1Layout.createSequentialGroup()
                                        .addComponent(MDP1MonthTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MDP1YearTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addGroup(MDP1Layout.createSequentialGroup()
                                        .addComponent(MDP1MonthLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MDP1YearLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(AddToDayConsumedTitleLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        MDP1Layout.setVerticalGroup(
            MDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MDP1Layout.createSequentialGroup()
                .addComponent(MDP1SelectDayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MDP1DayLbl)
                    .addComponent(MDP1MonthLbl)
                    .addComponent(MDP1YearLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MDP1DayTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MDP1MonthTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MDP1YearTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MDP1CreateDayRecordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MDP1DayNotif))
                .addGap(18, 18, 18)
                .addComponent(AddToDayConsumedTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MDP1AddMealComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MDP1AddFoodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MDP1AddDrinkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MDP1AddMealBtn)
                    .addComponent(MDP1AddFoodBtn)
                    .addComponent(MDP1AddDrinkBtn))
                .addGap(18, 18, 18)
                .addComponent(MDP1DayConsumedListLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MDP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CreateNewDayTitleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateNewDayTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MDP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MDP1DayTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MDP1DayTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MDP1DayTxtFieldActionPerformed

    private void MDP1MonthTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MDP1MonthTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MDP1MonthTxtFieldActionPerformed

    private void MDP1YearTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MDP1YearTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MDP1YearTxtFieldActionPerformed

    private void MDP1CreateDayRecordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MDP1CreateDayRecordBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MDP1CreateDayRecordBtnActionPerformed

    private void MDP1AddFoodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MDP1AddFoodBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MDP1AddFoodBtnActionPerformed

    private void MDP1AddDrinkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MDP1AddDrinkBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MDP1AddDrinkBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddToDayConsumedTitleLbl;
    private javax.swing.JLabel CreateNewDayTitleLbl;
    private javax.swing.JPanel MDP1;
    private javax.swing.JButton MDP1AddDrinkBtn;
    private javax.swing.JComboBox<String> MDP1AddDrinkComboBox;
    private javax.swing.JButton MDP1AddFoodBtn;
    private javax.swing.JComboBox<String> MDP1AddFoodComboBox;
    private javax.swing.JButton MDP1AddMealBtn;
    private javax.swing.JComboBox<String> MDP1AddMealComboBox;
    private javax.swing.JButton MDP1CreateDayRecordBtn;
    private javax.swing.JLabel MDP1DayConsumedListLbl;
    private javax.swing.JTextArea MDP1DayConsumedListOutput;
    private javax.swing.JLabel MDP1DayLbl;
    private javax.swing.JLabel MDP1DayNotif;
    private javax.swing.JTextField MDP1DayTxtField;
    private javax.swing.JLabel MDP1MonthLbl;
    private javax.swing.JTextField MDP1MonthTxtField;
    private javax.swing.JLabel MDP1SelectDayLbl;
    private javax.swing.JLabel MDP1YearLbl;
    private javax.swing.JTextField MDP1YearTxtField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
