/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nutrii.application.gui;

/**
 *
 * @author Blakey
 */
public class MngDietPnl21 extends javax.swing.JPanel {

/**
 * Creates new form MngDietPnl2
 */
public MngDietPnl21() {
    initComponents();
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewDaysLbl = new javax.swing.JLabel();
        MDP21 = new javax.swing.JPanel();
        ConsumedNutritionDataLbl = new javax.swing.JLabel();
        MDP21Output = new javax.swing.JPanel();

        ViewDaysLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ViewDaysLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ViewDaysLbl.setText("View Days");

        MDP21.setBackground(new java.awt.Color(102, 102, 102));

        ConsumedNutritionDataLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ConsumedNutritionDataLbl.setText("Consumed Nutrition Data");

        javax.swing.GroupLayout MDP21OutputLayout = new javax.swing.GroupLayout(MDP21Output);
        MDP21Output.setLayout(MDP21OutputLayout);
        MDP21OutputLayout.setHorizontalGroup(
            MDP21OutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );
        MDP21OutputLayout.setVerticalGroup(
            MDP21OutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MDP21Layout = new javax.swing.GroupLayout(MDP21);
        MDP21.setLayout(MDP21Layout);
        MDP21Layout.setHorizontalGroup(
            MDP21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MDP21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MDP21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MDP21Output, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConsumedNutritionDataLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        MDP21Layout.setVerticalGroup(
            MDP21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MDP21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ConsumedNutritionDataLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MDP21Output, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MDP21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewDaysLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ViewDaysLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MDP21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConsumedNutritionDataLbl;
    private javax.swing.JPanel MDP21;
    private javax.swing.JPanel MDP21Output;
    private javax.swing.JLabel ViewDaysLbl;
    // End of variables declaration//GEN-END:variables
}
