/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nutrii.application.gui;

/**
 *
 * @author Blakey
 */
public class MngDietPnl3 extends javax.swing.JPanel {

/**
 * Creates new form MngDietPnl3
 */
public MngDietPnl3() {
    initComponents();
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdjustADayTitleLbl = new javax.swing.JLabel();
        MDP3 = new javax.swing.JPanel();
        SelectDayLbl = new javax.swing.JLabel();
        DayLbl = new javax.swing.JLabel();
        DayTxtField = new javax.swing.JTextField();
        MonthLbl = new javax.swing.JLabel();
        MonthTxtField = new javax.swing.JTextField();
        YearLbl = new javax.swing.JLabel();
        YearTxtField = new javax.swing.JTextField();
        EnterDateBtn = new javax.swing.JButton();
        RemoveFromDayConsumedLbl = new javax.swing.JLabel();
        AddToDayConsumedLbl = new javax.swing.JLabel();
        AddMealComboBox = new javax.swing.JComboBox<>();
        AddMealBtn = new javax.swing.JButton();
        AddFoodComboBox = new javax.swing.JComboBox<>();
        AddFoodBtn = new javax.swing.JButton();
        AddDrinkComboBox = new javax.swing.JComboBox<>();
        AddDrinkBtn = new javax.swing.JButton();
        RemoveMealComboBox = new javax.swing.JComboBox<>();
        RemoveMealBtn = new javax.swing.JButton();
        RemoveFoodComboBox = new javax.swing.JComboBox<>();
        RemoveFoodBtn = new javax.swing.JButton();
        jComboBox6 = new javax.swing.JComboBox<>();
        RemoveDrinkBtn = new javax.swing.JButton();
        ViewDayBtn = new javax.swing.JButton();

        AdjustADayTitleLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AdjustADayTitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdjustADayTitleLbl.setText("Adjust a Day");

        MDP3.setBackground(new java.awt.Color(102, 102, 102));

        SelectDayLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SelectDayLbl.setText("Select Day");

        DayLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DayLbl.setForeground(new java.awt.Color(204, 204, 204));
        DayLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DayLbl.setText("DD");

        DayTxtField.setText("01");
        DayTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DayTxtFieldActionPerformed(evt);
            }
        });

        MonthLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MonthLbl.setForeground(new java.awt.Color(204, 204, 204));
        MonthLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MonthLbl.setText("MM");

        MonthTxtField.setText("01");
        MonthTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthTxtFieldActionPerformed(evt);
            }
        });

        YearLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        YearLbl.setForeground(new java.awt.Color(204, 204, 204));
        YearLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        YearLbl.setText("YYYY");

        YearTxtField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        YearTxtField.setText("2020");
        YearTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearTxtFieldActionPerformed(evt);
            }
        });

        EnterDateBtn.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        EnterDateBtn.setText("Enter Date");

        RemoveFromDayConsumedLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RemoveFromDayConsumedLbl.setForeground(new java.awt.Color(204, 204, 204));
        RemoveFromDayConsumedLbl.setText("Remove From Day Consumed List:");

        AddToDayConsumedLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddToDayConsumedLbl.setForeground(new java.awt.Color(204, 204, 204));
        AddToDayConsumedLbl.setText("Add to Day Consumed List:");

        AddMealComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        AddMealBtn.setText("Add Meal");

        AddFoodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        AddFoodBtn.setText("Add Food");
        AddFoodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFoodBtnActionPerformed(evt);
            }
        });

        AddDrinkComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        AddDrinkBtn.setText("Add Drink");
        AddDrinkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDrinkBtnActionPerformed(evt);
            }
        });

        RemoveMealComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        RemoveMealBtn.setText("Remove Meal");
        RemoveMealBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveMealBtnActionPerformed(evt);
            }
        });

        RemoveFoodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        RemoveFoodBtn.setText("Remove Food");
        RemoveFoodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveFoodBtnActionPerformed(evt);
            }
        });

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        RemoveDrinkBtn.setText("Remove Drink");
        RemoveDrinkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveDrinkBtnActionPerformed(evt);
            }
        });

        ViewDayBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ViewDayBtn.setForeground(new java.awt.Color(51, 102, 0));
        ViewDayBtn.setText("View Day");

        javax.swing.GroupLayout MDP3Layout = new javax.swing.GroupLayout(MDP3);
        MDP3.setLayout(MDP3Layout);
        MDP3Layout.setHorizontalGroup(
            MDP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MDP3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MDP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SelectDayLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RemoveFromDayConsumedLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MDP3Layout.createSequentialGroup()
                        .addGroup(MDP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ViewDayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MDP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(EnterDateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(MDP3Layout.createSequentialGroup()
                                    .addGroup(MDP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(DayTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(DayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(MDP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(MDP3Layout.createSequentialGroup()
                                            .addComponent(MonthTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(YearTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                        .addGroup(MDP3Layout.createSequentialGroup()
                                            .addComponent(MonthLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(YearLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(MDP3Layout.createSequentialGroup()
                                .addComponent(AddMealComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddFoodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddDrinkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MDP3Layout.createSequentialGroup()
                                .addComponent(AddMealBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddFoodBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddDrinkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MDP3Layout.createSequentialGroup()
                                .addComponent(RemoveMealComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RemoveFoodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MDP3Layout.createSequentialGroup()
                                .addComponent(RemoveMealBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RemoveFoodBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RemoveDrinkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 161, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(MDP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MDP3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(AddToDayConsumedLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        MDP3Layout.setVerticalGroup(
            MDP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MDP3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SelectDayLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MDP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DayLbl)
                    .addComponent(MonthLbl)
                    .addComponent(YearLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MDP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DayTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonthTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YearTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EnterDateBtn)
                .addGap(67, 67, 67)
                .addGroup(MDP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddMealComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddFoodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddDrinkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MDP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddMealBtn)
                    .addComponent(AddFoodBtn)
                    .addComponent(AddDrinkBtn))
                .addGap(39, 39, 39)
                .addComponent(RemoveFromDayConsumedLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MDP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemoveMealComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoveFoodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MDP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemoveMealBtn)
                    .addComponent(RemoveFoodBtn)
                    .addComponent(RemoveDrinkBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(ViewDayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(MDP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MDP3Layout.createSequentialGroup()
                    .addGap(136, 136, 136)
                    .addComponent(AddToDayConsumedLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(426, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MDP3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AdjustADayTitleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdjustADayTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MDP3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DayTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DayTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DayTxtFieldActionPerformed

    private void MonthTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonthTxtFieldActionPerformed

    private void YearTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearTxtFieldActionPerformed

    private void AddFoodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFoodBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddFoodBtnActionPerformed

    private void AddDrinkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDrinkBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddDrinkBtnActionPerformed

    private void RemoveFoodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveFoodBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoveFoodBtnActionPerformed

    private void RemoveDrinkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveDrinkBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoveDrinkBtnActionPerformed

    private void RemoveMealBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveMealBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoveMealBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDrinkBtn;
    private javax.swing.JComboBox<String> AddDrinkComboBox;
    private javax.swing.JButton AddFoodBtn;
    private javax.swing.JComboBox<String> AddFoodComboBox;
    private javax.swing.JButton AddMealBtn;
    private javax.swing.JComboBox<String> AddMealComboBox;
    private javax.swing.JLabel AddToDayConsumedLbl;
    private javax.swing.JLabel AdjustADayTitleLbl;
    private javax.swing.JLabel DayLbl;
    private javax.swing.JTextField DayTxtField;
    private javax.swing.JButton EnterDateBtn;
    private javax.swing.JPanel MDP3;
    private javax.swing.JLabel MonthLbl;
    private javax.swing.JTextField MonthTxtField;
    private javax.swing.JButton RemoveDrinkBtn;
    private javax.swing.JButton RemoveFoodBtn;
    private javax.swing.JComboBox<String> RemoveFoodComboBox;
    private javax.swing.JLabel RemoveFromDayConsumedLbl;
    private javax.swing.JButton RemoveMealBtn;
    private javax.swing.JComboBox<String> RemoveMealComboBox;
    private javax.swing.JLabel SelectDayLbl;
    private javax.swing.JButton ViewDayBtn;
    private javax.swing.JLabel YearLbl;
    private javax.swing.JTextField YearTxtField;
    private javax.swing.JComboBox<String> jComboBox6;
    // End of variables declaration//GEN-END:variables
}
