/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nutrii.application.gui;

/**
 *
 * @author Blakey
 */
public class MngRecordAddPnl extends javax.swing.JPanel {

/**
 * Creates new form AddConsumedPnl1
 */
public MngRecordAddPnl() {
    initComponents();
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        AddItemToRecordTitleLbl = new javax.swing.JLabel();
        MRAP = new javax.swing.JPanel();
        SelectRecordToAddToLbl = new javax.swing.JLabel();
        SelectRecordComboBox = new javax.swing.JComboBox<>();
        CaloriesLbl = new javax.swing.JLabel();
        TotalFatTxtField = new javax.swing.JTextField();
        ItemNamePnl = new javax.swing.JLabel();
        ItemNameTxtField = new javax.swing.JTextField();
        VitaminsLbl = new javax.swing.JLabel();
        MineralsLbl = new javax.swing.JLabel();
        VitaminB1Lbl = new javax.swing.JLabel();
        VitaminALbl = new javax.swing.JLabel();
        VitaminB2Lbl = new javax.swing.JLabel();
        VitaminB3Lbl = new javax.swing.JLabel();
        VitaminB5Lbl = new javax.swing.JLabel();
        VitaminB6Lbl = new javax.swing.JLabel();
        VitaminB7Lbl = new javax.swing.JLabel();
        VitaminB9Lbl = new javax.swing.JLabel();
        VitaminB12Lbl = new javax.swing.JLabel();
        VitaminCLbl = new javax.swing.JLabel();
        VitaminDLbl = new javax.swing.JLabel();
        VitaminELbl = new javax.swing.JLabel();
        VitaminKLbl = new javax.swing.JLabel();
        PercntageLbl1 = new javax.swing.JLabel();
        PercntageLbl2 = new javax.swing.JLabel();
        PercntageLbl3 = new javax.swing.JLabel();
        PercntageLbl4 = new javax.swing.JLabel();
        PercntageLbl5 = new javax.swing.JLabel();
        PercntageLbl6 = new javax.swing.JLabel();
        PercntageLbl7 = new javax.swing.JLabel();
        PercntageLbl8 = new javax.swing.JLabel();
        PercntageLbl9 = new javax.swing.JLabel();
        PercntageLbl10 = new javax.swing.JLabel();
        PercntageLbl11 = new javax.swing.JLabel();
        PercntageLbl12 = new javax.swing.JLabel();
        PercntageLbl13 = new javax.swing.JLabel();
        ProteinLbl = new javax.swing.JLabel();
        ProteinTxtField = new javax.swing.JTextField();
        CholesterolLbl = new javax.swing.JLabel();
        CholesterolTxtField = new javax.swing.JTextField();
        SaturatedFatLbl = new javax.swing.JLabel();
        TransFatLbl = new javax.swing.JLabel();
        CaloriesTxtField = new javax.swing.JTextField();
        TotalFatLbl = new javax.swing.JLabel();
        PolyunsaturatedFatLbl = new javax.swing.JLabel();
        MonounsaturatedFatLbl = new javax.swing.JLabel();
        SaturatedFatTxtField = new javax.swing.JTextField();
        TransFatTxtField = new javax.swing.JTextField();
        PolyunsaturatedTxtField = new javax.swing.JTextField();
        MonounsaturatedTxtField = new javax.swing.JTextField();
        TotalCarbohydrateLbl = new javax.swing.JLabel();
        DietaryFiberLbl = new javax.swing.JLabel();
        SugarsLbl = new javax.swing.JLabel();
        AddedSugarsLbl = new javax.swing.JLabel();
        TotalCarbohydratesTxtField = new javax.swing.JTextField();
        DietaryFiberTxtField = new javax.swing.JTextField();
        SugarsTxtField = new javax.swing.JTextField();
        AddedSugarsTxtField = new javax.swing.JTextField();
        SodiumLbl = new javax.swing.JLabel();
        PotassiumLbl = new javax.swing.JLabel();
        CalciumLbl = new javax.swing.JLabel();
        PhosphorusLbl = new javax.swing.JLabel();
        MagnesiumLbl = new javax.swing.JLabel();
        SulfurLbl = new javax.swing.JLabel();
        IronLbl = new javax.swing.JLabel();
        ChromiumLbl = new javax.swing.JLabel();
        CoboltLbl = new javax.swing.JLabel();
        CopperLbl = new javax.swing.JLabel();
        ZincLbl = new javax.swing.JLabel();
        ManganeseLbl = new javax.swing.JLabel();
        MolybdenumLbl = new javax.swing.JLabel();
        IodineLbl = new javax.swing.JLabel();
        SeleniumLbl = new javax.swing.JLabel();
        FluorideLbl = new javax.swing.JLabel();
        MgLbl1 = new javax.swing.JLabel();
        MgLbl2 = new javax.swing.JLabel();
        PercntageLbl14 = new javax.swing.JLabel();
        PercntageLbl15 = new javax.swing.JLabel();
        PercntageLbl16 = new javax.swing.JLabel();
        PercntageLbl17 = new javax.swing.JLabel();
        PercntageLbl18 = new javax.swing.JLabel();
        PercntageLbl19 = new javax.swing.JLabel();
        PercntageLbl20 = new javax.swing.JLabel();
        PercntageLbl21 = new javax.swing.JLabel();
        PercntageLbl22 = new javax.swing.JLabel();
        PercntageLbl23 = new javax.swing.JLabel();
        PercntageLbl24 = new javax.swing.JLabel();
        PercntageLbl25 = new javax.swing.JLabel();
        PercntageLbl26 = new javax.swing.JLabel();
        PercntageLbl27 = new javax.swing.JLabel();
        VitaminATxtField = new javax.swing.JTextField();
        VitaminB1TxtField = new javax.swing.JTextField();
        VitaminB2TxtField = new javax.swing.JTextField();
        VitaminB3TxtField = new javax.swing.JTextField();
        VitaminB5TxtField = new javax.swing.JTextField();
        VitaminB6TxtField = new javax.swing.JTextField();
        VitaminB7TxtField = new javax.swing.JTextField();
        VitaminB9TxtField = new javax.swing.JTextField();
        VitaminB12TxtField = new javax.swing.JTextField();
        VitaminCTxtField = new javax.swing.JTextField();
        VitaminDTxtField = new javax.swing.JTextField();
        VitaminETxtField = new javax.swing.JTextField();
        VitaminKTxtField = new javax.swing.JTextField();
        MineralSodiumTxtField = new javax.swing.JTextField();
        MineralPotassiumTxtField = new javax.swing.JTextField();
        MineralCalciumTxtField = new javax.swing.JTextField();
        MineralPhosphorusTxtField = new javax.swing.JTextField();
        MineralMagnesiumTxtField = new javax.swing.JTextField();
        MineralSulfurTxtField = new javax.swing.JTextField();
        MineralIronTxtField = new javax.swing.JTextField();
        MineralChromiumTxtField = new javax.swing.JTextField();
        MineralCoboltTxtField = new javax.swing.JTextField();
        MineralCopperTxtField = new javax.swing.JTextField();
        MineralZincTxtField = new javax.swing.JTextField();
        MineralManganeseTxtField = new javax.swing.JTextField();
        MineralMolybdenumTxtField = new javax.swing.JTextField();
        MineralIodineTxtField = new javax.swing.JTextField();
        MineralSeleniumTxtField = new javax.swing.JTextField();
        MineralFluorideTxtField = new javax.swing.JTextField();
        AddItemToRecordBtn = new javax.swing.JButton();

        jLabel14.setText("Vitamin B7(Biotin)");

        jLabel18.setText("Vitamin C");

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("%");

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("%");

        AddItemToRecordTitleLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AddItemToRecordTitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddItemToRecordTitleLbl.setText("Add Item To Record");

        MRAP.setBackground(new java.awt.Color(102, 102, 102));

        SelectRecordToAddToLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SelectRecordToAddToLbl.setText("Select Record to Add to");

        SelectRecordComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food", "Drink" }));

        CaloriesLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CaloriesLbl.setText("Calories");

        ItemNamePnl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ItemNamePnl.setText("Item Name");

        VitaminsLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        VitaminsLbl.setText("Vitamins");

        MineralsLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MineralsLbl.setText("Minerals");

        VitaminB1Lbl.setText("Vitamin B1(Thiamine)");

        VitaminALbl.setText("Vitamin A");

        VitaminB2Lbl.setText("Vitamin B2(Riboflavin)");

        VitaminB3Lbl.setText("Vitamin B3(Niacin)");

        VitaminB5Lbl.setText("Vitamin B5(Pantothenic Acid)");

        VitaminB6Lbl.setText("Vitamin B6(Pyridoxine)");

        VitaminB7Lbl.setText("Vitamin B7(Biotin)");

        VitaminB9Lbl.setText("Vitamin B9(Folate)");

        VitaminB12Lbl.setText("Vitamin B12(Cobalamin)");

        VitaminCLbl.setText("Vitamin C");

        VitaminDLbl.setText("Vitamin D");

        VitaminELbl.setText("Vitamin E");

        VitaminKLbl.setText("Vitamin K");

        PercntageLbl1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl1.setText("%");

        PercntageLbl2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl2.setText("%");

        PercntageLbl3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl3.setText("%");

        PercntageLbl4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl4.setText("%");

        PercntageLbl5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl5.setText("%");

        PercntageLbl6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl6.setText("%");

        PercntageLbl7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl7.setText("%");

        PercntageLbl8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl8.setText("%");

        PercntageLbl9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl9.setText("%");

        PercntageLbl10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl10.setText("%");

        PercntageLbl11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl11.setText("%");

        PercntageLbl12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl12.setText("%");

        PercntageLbl13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl13.setText("%");

        ProteinLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ProteinLbl.setText("Protein");

        ProteinTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProteinTxtFieldActionPerformed(evt);
            }
        });

        CholesterolLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CholesterolLbl.setText("Cholesterol");

        SaturatedFatLbl.setText("Saturated Fat");

        TransFatLbl.setText("Trans Fat");

        TotalFatLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TotalFatLbl.setText("Total Fat");

        PolyunsaturatedFatLbl.setText("Polyunsaturated");

        MonounsaturatedFatLbl.setText("Monounsaturated");

        TotalCarbohydrateLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TotalCarbohydrateLbl.setText("Total Carbohydrate");

        DietaryFiberLbl.setText("Dietary Fiber");

        SugarsLbl.setText("Sugars");

        AddedSugarsLbl.setText("Added Sugars");

        SodiumLbl.setText("Sodium");

        PotassiumLbl.setText("Potassium");

        CalciumLbl.setText("Calcium");

        PhosphorusLbl.setText("Phosphorus");

        MagnesiumLbl.setText("Magnesium");

        SulfurLbl.setText("Sulfur");

        IronLbl.setText("Iron");

        ChromiumLbl.setText("Chromium");

        CoboltLbl.setText("Cobolt");

        CopperLbl.setText("Copper");

        ZincLbl.setText("Zinc");

        ManganeseLbl.setText("Manganese");
        ManganeseLbl.setToolTipText("");

        MolybdenumLbl.setText("Molybdenum");

        IodineLbl.setText("Iodine");

        SeleniumLbl.setText("Selenium");

        FluorideLbl.setText("Fluoride");

        MgLbl1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        MgLbl1.setText("mg");

        MgLbl2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        MgLbl2.setText("mg");

        PercntageLbl14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl14.setText("%");

        PercntageLbl15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl15.setText("%");

        PercntageLbl16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl16.setText("%");

        PercntageLbl17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl17.setText("%");

        PercntageLbl18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl18.setText("%");

        PercntageLbl19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl19.setText("%");

        PercntageLbl20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl20.setText("%");

        PercntageLbl21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl21.setText("%");

        PercntageLbl22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl22.setText("%");

        PercntageLbl23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl23.setText("%");

        PercntageLbl24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl24.setText("%");

        PercntageLbl25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl25.setText("%");

        PercntageLbl26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl26.setText("%");

        PercntageLbl27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl27.setText("%");

        VitaminB5TxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VitaminB5TxtFieldActionPerformed(evt);
            }
        });

        AddItemToRecordBtn.setForeground(new java.awt.Color(0, 102, 0));
        AddItemToRecordBtn.setText("Add Item To Record");

        javax.swing.GroupLayout MRAPLayout = new javax.swing.GroupLayout(MRAP);
        MRAP.setLayout(MRAPLayout);
        MRAPLayout.setHorizontalGroup(
            MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MRAPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MRAPLayout.createSequentialGroup()
                        .addComponent(SelectRecordToAddToLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ItemNamePnl, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MRAPLayout.createSequentialGroup()
                        .addComponent(SelectRecordComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(ItemNameTxtField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MRAPLayout.createSequentialGroup()
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MRAPLayout.createSequentialGroup()
                                .addComponent(VitaminsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MRAPLayout.createSequentialGroup()
                                .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(AddItemToRecordBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(MRAPLayout.createSequentialGroup()
                                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(MRAPLayout.createSequentialGroup()
                                                .addComponent(VitaminKLbl)
                                                .addGap(105, 105, 105))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MRAPLayout.createSequentialGroup()
                                                .addComponent(VitaminELbl)
                                                .addGap(106, 106, 106))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MRAPLayout.createSequentialGroup()
                                                .addComponent(VitaminDLbl)
                                                .addGap(104, 104, 104))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MRAPLayout.createSequentialGroup()
                                                .addComponent(VitaminCLbl)
                                                .addGap(104, 104, 104))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MRAPLayout.createSequentialGroup()
                                                .addComponent(VitaminB12Lbl)
                                                .addGap(27, 27, 27))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MRAPLayout.createSequentialGroup()
                                                .addComponent(VitaminB9Lbl)
                                                .addGap(59, 59, 59))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MRAPLayout.createSequentialGroup()
                                                .addComponent(VitaminB7Lbl)
                                                .addGap(60, 60, 60))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MRAPLayout.createSequentialGroup()
                                                .addComponent(VitaminB6Lbl)
                                                .addGap(35, 35, 35))
                                            .addComponent(VitaminB5Lbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MRAPLayout.createSequentialGroup()
                                                .addComponent(VitaminB3Lbl)
                                                .addGap(57, 57, 57))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MRAPLayout.createSequentialGroup()
                                                .addComponent(VitaminB2Lbl)
                                                .addGap(38, 38, 38))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MRAPLayout.createSequentialGroup()
                                                .addComponent(VitaminB1Lbl)
                                                .addGap(42, 42, 42))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MRAPLayout.createSequentialGroup()
                                                .addComponent(VitaminALbl)
                                                .addGap(104, 104, 104)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(VitaminKTxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(VitaminETxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(VitaminDTxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(VitaminCTxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(VitaminB12TxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(VitaminB9TxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(VitaminB7TxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(VitaminB6TxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(VitaminB5TxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(VitaminB3TxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(VitaminB2TxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(VitaminB1TxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(VitaminATxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(PercntageLbl13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PercntageLbl12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PercntageLbl11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PercntageLbl10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PercntageLbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PercntageLbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PercntageLbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PercntageLbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PercntageLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PercntageLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PercntageLbl1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PercntageLbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PercntageLbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)))
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MineralsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MRAPLayout.createSequentialGroup()
                                .addComponent(PhosphorusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MineralPhosphorusTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(MRAPLayout.createSequentialGroup()
                                .addComponent(MagnesiumLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MineralMagnesiumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(MRAPLayout.createSequentialGroup()
                                .addComponent(SulfurLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MineralSulfurTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(MRAPLayout.createSequentialGroup()
                                .addComponent(IronLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MineralIronTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(MRAPLayout.createSequentialGroup()
                                .addComponent(ChromiumLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MineralChromiumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(MRAPLayout.createSequentialGroup()
                                .addComponent(CoboltLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MineralCoboltTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(MRAPLayout.createSequentialGroup()
                                .addComponent(CopperLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MineralCopperTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(MRAPLayout.createSequentialGroup()
                                .addComponent(ZincLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MineralZincTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(MRAPLayout.createSequentialGroup()
                                .addComponent(ManganeseLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MineralManganeseTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(MRAPLayout.createSequentialGroup()
                                .addComponent(MolybdenumLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MineralMolybdenumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(MRAPLayout.createSequentialGroup()
                                .addComponent(IodineLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MineralIodineTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(MRAPLayout.createSequentialGroup()
                                .addComponent(SeleniumLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MineralSeleniumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(MRAPLayout.createSequentialGroup()
                                .addComponent(FluorideLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MineralFluorideTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MRAPLayout.createSequentialGroup()
                                .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MRAPLayout.createSequentialGroup()
                                        .addComponent(SodiumLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(MineralSodiumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(MRAPLayout.createSequentialGroup()
                                        .addComponent(CalciumLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(MineralCalciumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(MRAPLayout.createSequentialGroup()
                                        .addComponent(PotassiumLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(MineralPotassiumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MgLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MgLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(MRAPLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PercntageLbl15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PercntageLbl14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PercntageLbl16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PercntageLbl17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PercntageLbl18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PercntageLbl19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PercntageLbl20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PercntageLbl21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PercntageLbl22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PercntageLbl23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PercntageLbl24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PercntageLbl25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PercntageLbl26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PercntageLbl27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(13, 13, 13))))
                    .addGroup(MRAPLayout.createSequentialGroup()
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CaloriesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(CholesterolLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CholesterolTxtField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ProteinLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProteinTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CaloriesTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PolyunsaturatedFatLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MonounsaturatedFatLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(MRAPLayout.createSequentialGroup()
                                .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(TotalFatLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SaturatedFatLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TransFatLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MRAPLayout.createSequentialGroup()
                                .addComponent(TransFatTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SugarsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SugarsTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MRAPLayout.createSequentialGroup()
                                .addComponent(SaturatedFatTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DietaryFiberLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DietaryFiberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MRAPLayout.createSequentialGroup()
                                .addComponent(PolyunsaturatedTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(AddedSugarsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddedSugarsTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(MonounsaturatedTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MRAPLayout.createSequentialGroup()
                                .addComponent(TotalFatTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TotalCarbohydrateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TotalCarbohydratesTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)))
                .addContainerGap())
        );
        MRAPLayout.setVerticalGroup(
            MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MRAPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SelectRecordToAddToLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ItemNamePnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectRecordComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemNameTxtField))
                .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MRAPLayout.createSequentialGroup()
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MRAPLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TotalCarbohydrateLbl)
                                    .addComponent(TotalCarbohydratesTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MRAPLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TotalFatTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TotalFatLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SaturatedFatLbl)
                            .addComponent(SaturatedFatTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DietaryFiberLbl)
                            .addComponent(DietaryFiberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TransFatTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SugarsLbl)
                            .addComponent(SugarsTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TransFatLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(PolyunsaturatedTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PolyunsaturatedFatLbl))
                            .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(AddedSugarsLbl)
                                .addComponent(AddedSugarsTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MonounsaturatedFatLbl)
                            .addComponent(MonounsaturatedTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MRAPLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CaloriesLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CaloriesTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(CholesterolLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CholesterolTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProteinLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProteinTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VitaminsLbl)
                    .addComponent(MineralsLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MRAPLayout.createSequentialGroup()
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VitaminALbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SodiumLbl)
                                .addComponent(MgLbl1)
                                .addComponent(MineralSodiumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VitaminB1Lbl)
                            .addComponent(PotassiumLbl)
                            .addComponent(MgLbl2)
                            .addComponent(MineralPotassiumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VitaminB2Lbl)
                            .addComponent(CalciumLbl)
                            .addComponent(PercntageLbl14)
                            .addComponent(MineralCalciumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VitaminB3Lbl)
                            .addComponent(PhosphorusLbl)
                            .addComponent(PercntageLbl15)
                            .addComponent(MineralPhosphorusTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VitaminB5Lbl)
                            .addComponent(MagnesiumLbl)
                            .addComponent(PercntageLbl16)
                            .addComponent(MineralMagnesiumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VitaminB6Lbl)
                            .addComponent(SulfurLbl)
                            .addComponent(PercntageLbl17)
                            .addComponent(MineralSulfurTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VitaminB7Lbl)
                            .addComponent(IronLbl)
                            .addComponent(PercntageLbl18)
                            .addComponent(MineralIronTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VitaminB9Lbl)
                            .addComponent(ChromiumLbl)
                            .addComponent(PercntageLbl19)
                            .addComponent(MineralChromiumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VitaminB12Lbl)
                            .addComponent(CoboltLbl)
                            .addComponent(PercntageLbl20)
                            .addComponent(MineralCoboltTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VitaminCLbl)
                            .addComponent(CopperLbl)
                            .addComponent(PercntageLbl21)
                            .addComponent(MineralCopperTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VitaminDLbl)
                            .addComponent(ZincLbl)
                            .addComponent(PercntageLbl22)
                            .addComponent(MineralZincTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VitaminELbl)
                            .addComponent(ManganeseLbl)
                            .addComponent(PercntageLbl23)
                            .addComponent(MineralManganeseTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VitaminKLbl)
                            .addComponent(MolybdenumLbl)
                            .addComponent(PercntageLbl24)
                            .addComponent(MineralMolybdenumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MRAPLayout.createSequentialGroup()
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PercntageLbl1)
                            .addComponent(VitaminATxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PercntageLbl2)
                            .addComponent(VitaminB1TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PercntageLbl3)
                            .addComponent(VitaminB2TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PercntageLbl4)
                            .addComponent(VitaminB3TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PercntageLbl5)
                            .addComponent(VitaminB5TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PercntageLbl6)
                            .addComponent(VitaminB6TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PercntageLbl7)
                            .addComponent(VitaminB7TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PercntageLbl8)
                            .addComponent(VitaminB9TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PercntageLbl9)
                            .addComponent(VitaminB12TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PercntageLbl10)
                            .addComponent(VitaminCTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PercntageLbl11)
                            .addComponent(VitaminDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PercntageLbl12)
                            .addComponent(VitaminETxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PercntageLbl13)
                            .addComponent(VitaminKTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IodineLbl)
                    .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PercntageLbl25)
                        .addComponent(MineralIodineTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MRAPLayout.createSequentialGroup()
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SeleniumLbl)
                            .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(PercntageLbl26)
                                .addComponent(MineralSeleniumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MRAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FluorideLbl)
                            .addComponent(PercntageLbl27)
                            .addComponent(MineralFluorideTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(AddItemToRecordBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddItemToRecordTitleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MRAP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AddItemToRecordTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MRAP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void VitaminB5TxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VitaminB5TxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VitaminB5TxtFieldActionPerformed

    private void ProteinTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProteinTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProteinTxtFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddItemToRecordBtn;
    private javax.swing.JLabel AddItemToRecordTitleLbl;
    private javax.swing.JLabel AddedSugarsLbl;
    private javax.swing.JTextField AddedSugarsTxtField;
    private javax.swing.JLabel CalciumLbl;
    private javax.swing.JLabel CaloriesLbl;
    private javax.swing.JTextField CaloriesTxtField;
    private javax.swing.JLabel CholesterolLbl;
    private javax.swing.JTextField CholesterolTxtField;
    private javax.swing.JLabel ChromiumLbl;
    private javax.swing.JLabel CoboltLbl;
    private javax.swing.JLabel CopperLbl;
    private javax.swing.JLabel DietaryFiberLbl;
    private javax.swing.JTextField DietaryFiberTxtField;
    private javax.swing.JLabel FluorideLbl;
    private javax.swing.JLabel IodineLbl;
    private javax.swing.JLabel IronLbl;
    private javax.swing.JLabel ItemNamePnl;
    private javax.swing.JTextField ItemNameTxtField;
    private javax.swing.JPanel MRAP;
    private javax.swing.JLabel MagnesiumLbl;
    private javax.swing.JLabel ManganeseLbl;
    private javax.swing.JLabel MgLbl1;
    private javax.swing.JLabel MgLbl2;
    private javax.swing.JTextField MineralCalciumTxtField;
    private javax.swing.JTextField MineralChromiumTxtField;
    private javax.swing.JTextField MineralCoboltTxtField;
    private javax.swing.JTextField MineralCopperTxtField;
    private javax.swing.JTextField MineralFluorideTxtField;
    private javax.swing.JTextField MineralIodineTxtField;
    private javax.swing.JTextField MineralIronTxtField;
    private javax.swing.JTextField MineralMagnesiumTxtField;
    private javax.swing.JTextField MineralManganeseTxtField;
    private javax.swing.JTextField MineralMolybdenumTxtField;
    private javax.swing.JTextField MineralPhosphorusTxtField;
    private javax.swing.JTextField MineralPotassiumTxtField;
    private javax.swing.JTextField MineralSeleniumTxtField;
    private javax.swing.JTextField MineralSodiumTxtField;
    private javax.swing.JTextField MineralSulfurTxtField;
    private javax.swing.JTextField MineralZincTxtField;
    private javax.swing.JLabel MineralsLbl;
    private javax.swing.JLabel MolybdenumLbl;
    private javax.swing.JLabel MonounsaturatedFatLbl;
    private javax.swing.JTextField MonounsaturatedTxtField;
    private javax.swing.JLabel PercntageLbl1;
    private javax.swing.JLabel PercntageLbl10;
    private javax.swing.JLabel PercntageLbl11;
    private javax.swing.JLabel PercntageLbl12;
    private javax.swing.JLabel PercntageLbl13;
    private javax.swing.JLabel PercntageLbl14;
    private javax.swing.JLabel PercntageLbl15;
    private javax.swing.JLabel PercntageLbl16;
    private javax.swing.JLabel PercntageLbl17;
    private javax.swing.JLabel PercntageLbl18;
    private javax.swing.JLabel PercntageLbl19;
    private javax.swing.JLabel PercntageLbl2;
    private javax.swing.JLabel PercntageLbl20;
    private javax.swing.JLabel PercntageLbl21;
    private javax.swing.JLabel PercntageLbl22;
    private javax.swing.JLabel PercntageLbl23;
    private javax.swing.JLabel PercntageLbl24;
    private javax.swing.JLabel PercntageLbl25;
    private javax.swing.JLabel PercntageLbl26;
    private javax.swing.JLabel PercntageLbl27;
    private javax.swing.JLabel PercntageLbl3;
    private javax.swing.JLabel PercntageLbl4;
    private javax.swing.JLabel PercntageLbl5;
    private javax.swing.JLabel PercntageLbl6;
    private javax.swing.JLabel PercntageLbl7;
    private javax.swing.JLabel PercntageLbl8;
    private javax.swing.JLabel PercntageLbl9;
    private javax.swing.JLabel PhosphorusLbl;
    private javax.swing.JLabel PolyunsaturatedFatLbl;
    private javax.swing.JTextField PolyunsaturatedTxtField;
    private javax.swing.JLabel PotassiumLbl;
    private javax.swing.JLabel ProteinLbl;
    private javax.swing.JTextField ProteinTxtField;
    private javax.swing.JLabel SaturatedFatLbl;
    private javax.swing.JTextField SaturatedFatTxtField;
    private javax.swing.JComboBox<String> SelectRecordComboBox;
    private javax.swing.JLabel SelectRecordToAddToLbl;
    private javax.swing.JLabel SeleniumLbl;
    private javax.swing.JLabel SodiumLbl;
    private javax.swing.JLabel SugarsLbl;
    private javax.swing.JTextField SugarsTxtField;
    private javax.swing.JLabel SulfurLbl;
    private javax.swing.JLabel TotalCarbohydrateLbl;
    private javax.swing.JTextField TotalCarbohydratesTxtField;
    private javax.swing.JLabel TotalFatLbl;
    private javax.swing.JTextField TotalFatTxtField;
    private javax.swing.JLabel TransFatLbl;
    private javax.swing.JTextField TransFatTxtField;
    private javax.swing.JLabel VitaminALbl;
    private javax.swing.JTextField VitaminATxtField;
    private javax.swing.JLabel VitaminB12Lbl;
    private javax.swing.JTextField VitaminB12TxtField;
    private javax.swing.JLabel VitaminB1Lbl;
    private javax.swing.JTextField VitaminB1TxtField;
    private javax.swing.JLabel VitaminB2Lbl;
    private javax.swing.JTextField VitaminB2TxtField;
    private javax.swing.JLabel VitaminB3Lbl;
    private javax.swing.JTextField VitaminB3TxtField;
    private javax.swing.JLabel VitaminB5Lbl;
    private javax.swing.JTextField VitaminB5TxtField;
    private javax.swing.JLabel VitaminB6Lbl;
    private javax.swing.JTextField VitaminB6TxtField;
    private javax.swing.JLabel VitaminB7Lbl;
    private javax.swing.JTextField VitaminB7TxtField;
    private javax.swing.JLabel VitaminB9Lbl;
    private javax.swing.JTextField VitaminB9TxtField;
    private javax.swing.JLabel VitaminCLbl;
    private javax.swing.JTextField VitaminCTxtField;
    private javax.swing.JLabel VitaminDLbl;
    private javax.swing.JTextField VitaminDTxtField;
    private javax.swing.JLabel VitaminELbl;
    private javax.swing.JTextField VitaminETxtField;
    private javax.swing.JLabel VitaminKLbl;
    private javax.swing.JTextField VitaminKTxtField;
    private javax.swing.JLabel VitaminsLbl;
    private javax.swing.JLabel ZincLbl;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel33;
    // End of variables declaration//GEN-END:variables
}
