/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nutrii.application.gui;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Blakey
 */
public class MngRecordRemovePnl extends javax.swing.JPanel {

    /**
     * Creates new form MngItemsPnl1
     */
    int xMouse;
    int yMouse;

    public MngRecordRemovePnl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MRRP = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        SelectRecordComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        SelectItemComboBox = new javax.swing.JComboBox<>();
        RemoveItemBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bckBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(790, 790));
        setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(790, 790));
        jPanel1.setLayout(null);

        MRRP.setBackground(new java.awt.Color(15, 93, 70));
        MRRP.setPreferredSize(new java.awt.Dimension(790, 790));
        MRRP.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Select Record to Remove From");
        MRRP.add(jLabel2);
        jLabel2.setBounds(140, 60, 350, 30);

        SelectRecordComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SelectRecordComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type ", "Food", "Drink" }));
        SelectRecordComboBox.setBorder(null);
        SelectRecordComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectRecordComboBoxActionPerformed(evt);
            }
        });
        MRRP.add(SelectRecordComboBox);
        SelectRecordComboBox.setBounds(150, 110, 319, 59);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Select Item From Record");
        MRRP.add(jLabel3);
        jLabel3.setBounds(160, 240, 290, 30);

        SelectItemComboBox.setMaximumRowCount(50);
        SelectItemComboBox.setAutoscrolls(true);
        SelectItemComboBox.setBorder(null);
        MRRP.add(SelectItemComboBox);
        SelectItemComboBox.setBounds(150, 300, 319, 59);

        RemoveItemBtn.setBackground(new java.awt.Color(10, 36, 2));
        RemoveItemBtn.setForeground(new java.awt.Color(255, 255, 255));
        RemoveItemBtn.setText("Remove Item");
        RemoveItemBtn.setBorder(null);
        RemoveItemBtn.setBorderPainted(false);
        RemoveItemBtn.setFocusPainted(false);
        MRRP.add(RemoveItemBtn);
        RemoveItemBtn.setBounds(210, 430, 190, 58);

        jPanel1.add(MRRP);
        MRRP.setBounds(0, 76, 790, 790);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(790, 76));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REMOVE FROM DATABASE");

        bckBtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        bckBtn.setForeground(new java.awt.Color(255, 255, 255));
        bckBtn.setText("< Back");
        bckBtn.setBorder(null);
        bckBtn.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bckBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jLabel1)
                .addContainerGap(259, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(25, Short.MAX_VALUE))
            .addComponent(bckBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 690, 76);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 790, 790);
    }// </editor-fold>//GEN-END:initComponents

    private void SelectRecordComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectRecordComboBoxActionPerformed
//            SelectItemComboBox.addActionListener(a);
    }//GEN-LAST:event_SelectRecordComboBoxActionPerformed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        parentFrame.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    public JComboBox<String> getSelectItemComboBox() {
        return SelectItemComboBox;
    }

    public JComboBox<String> getSelectRecordComboBox() {
        return SelectRecordComboBox;
    }

    public void addRecordListener(ActionListener a) {
        SelectRecordComboBox.addActionListener(a);
    }

    public void addRemoveBtnListener(ActionListener a) {
        RemoveItemBtn.addActionListener(a);
    }

    public void clearRecordComboBox() {
        SelectRecordComboBox.setSelectedIndex(0);
    }

    public void clearItemComboBox() {
        ArrayList<String> model = new ArrayList<>();
        model.add("");
        DefaultComboBoxModel defaultModel = new DefaultComboBoxModel(model.toArray());
        SelectItemComboBox.setModel(defaultModel);
    }

    public void setItemModel(DefaultComboBoxModel m) {
        SelectItemComboBox.setModel(m);
    }
    
    public void addBackBtnListener(ActionListener a){
        bckBtn.addActionListener(a);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MRRP;
    private javax.swing.JButton RemoveItemBtn;
    private javax.swing.JComboBox<String> SelectItemComboBox;
    private javax.swing.JComboBox<String> SelectRecordComboBox;
    private javax.swing.JButton bckBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
