/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nutrii.application.gui;

import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.UIManager;
import javax.swing.text.Keymap;

/**
 *
 * @author Blakey
 */
public class MngRecordAddPnl extends javax.swing.JPanel {

    /**
     * Creates new form AddConsumedPnl1
     */
    ArrayList<JTextField> textFields;

    public MngRecordAddPnl() {
        textFields = new ArrayList<>();
        initComponents();
        setInitValues();
    }

    public void setInitValues() {
        for (JTextField f : textFields) {
            if (f.getName() == "foodName") {
                f.setText(null);
            } else {
                f.setText("0");
            }
        }
    }

    public ArrayList<JTextField> getTextFields() {
        return textFields;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        AddItemToRecordTitleLbl = new javax.swing.JLabel();
        MRAP = new javax.swing.JPanel();
        SelectRecordToAddToLbl = new javax.swing.JLabel();
        SelectRecordComboBox = new javax.swing.JComboBox<>();
        CaloriesLbl = new javax.swing.JLabel();
        TotalFatTxtField = new javax.swing.JTextField();
        this.textFields.add(TotalFatTxtField);
        ItemNamePnl = new javax.swing.JLabel();
        ItemNameTxtField = new javax.swing.JTextField();
        VitaminsLbl = new javax.swing.JLabel();
        MineralsLbl = new javax.swing.JLabel();
        VitaminB1Lbl = new javax.swing.JLabel();
        VitaminALbl = new javax.swing.JLabel();
        VitaminB2Lbl = new javax.swing.JLabel();
        VitaminB3Lbl = new javax.swing.JLabel();
        VitaminB5Lbl = new javax.swing.JLabel();
        VitaminB6Lbl = new javax.swing.JLabel();
        VitaminB7Lbl = new javax.swing.JLabel();
        VitaminB9Lbl = new javax.swing.JLabel();
        VitaminB12Lbl = new javax.swing.JLabel();
        VitaminCLbl = new javax.swing.JLabel();
        VitaminDLbl = new javax.swing.JLabel();
        VitaminELbl = new javax.swing.JLabel();
        VitaminKLbl = new javax.swing.JLabel();
        PercntageLbl1 = new javax.swing.JLabel();
        PercntageLbl2 = new javax.swing.JLabel();
        PercntageLbl3 = new javax.swing.JLabel();
        PercntageLbl4 = new javax.swing.JLabel();
        PercntageLbl5 = new javax.swing.JLabel();
        PercntageLbl6 = new javax.swing.JLabel();
        PercntageLbl7 = new javax.swing.JLabel();
        PercntageLbl8 = new javax.swing.JLabel();
        PercntageLbl9 = new javax.swing.JLabel();
        PercntageLbl10 = new javax.swing.JLabel();
        PercntageLbl11 = new javax.swing.JLabel();
        PercntageLbl12 = new javax.swing.JLabel();
        PercntageLbl13 = new javax.swing.JLabel();
        ProteinLbl = new javax.swing.JLabel();
        ProteinTxtField = new javax.swing.JTextField();
        this.textFields.add(ProteinTxtField);
        CholesterolLbl = new javax.swing.JLabel();
        CholesterolTxtField = new javax.swing.JTextField();
        this.textFields.add(CholesterolTxtField);
        SaturatedFatLbl = new javax.swing.JLabel();
        TransFatLbl = new javax.swing.JLabel();
        CaloriesTxtField = new javax.swing.JTextField();
        this.textFields.add(CaloriesTxtField);
        TotalFatLbl = new javax.swing.JLabel();
        PolyunsaturatedFatLbl = new javax.swing.JLabel();
        MonounsaturatedFatLbl = new javax.swing.JLabel();
        SaturatedFatTxtField = new javax.swing.JTextField();
        this.textFields.add(SaturatedFatTxtField);
        TransFatTxtField = new javax.swing.JTextField();
        this.textFields.add(TransFatTxtField);
        PolyunsaturatedTxtField = new javax.swing.JTextField();
        this.textFields.add(PolyunsaturatedTxtField);
        MonounsaturatedTxtField = new javax.swing.JTextField();
        this.textFields.add(MonounsaturatedTxtField);
        TotalCarbohydrateLbl = new javax.swing.JLabel();
        DietaryFiberLbl = new javax.swing.JLabel();
        SugarsLbl = new javax.swing.JLabel();
        AddedSugarsLbl = new javax.swing.JLabel();
        TotalCarbohydratesTxtField = new javax.swing.JTextField();
        this.textFields.add(TotalCarbohydratesTxtField);
        DietaryFiberTxtField = new javax.swing.JTextField();
        this.textFields.add(DietaryFiberTxtField);
        SugarsTxtField = new javax.swing.JTextField();
        this.textFields.add(SugarsTxtField);
        AddedSugarsTxtField = new javax.swing.JTextField();
        this.textFields.add(AddedSugarsTxtField);
        SodiumLbl = new javax.swing.JLabel();
        PotassiumLbl = new javax.swing.JLabel();
        CalciumLbl = new javax.swing.JLabel();
        PhosphorusLbl = new javax.swing.JLabel();
        MagnesiumLbl = new javax.swing.JLabel();
        SulfurLbl = new javax.swing.JLabel();
        IronLbl = new javax.swing.JLabel();
        ChromiumLbl = new javax.swing.JLabel();
        CoboltLbl = new javax.swing.JLabel();
        CopperLbl = new javax.swing.JLabel();
        ZincLbl = new javax.swing.JLabel();
        ManganeseLbl = new javax.swing.JLabel();
        MolybdenumLbl = new javax.swing.JLabel();
        IodineLbl = new javax.swing.JLabel();
        SeleniumLbl = new javax.swing.JLabel();
        FluorideLbl = new javax.swing.JLabel();
        MgLbl1 = new javax.swing.JLabel();
        MgLbl2 = new javax.swing.JLabel();
        PercntageLbl14 = new javax.swing.JLabel();
        PercntageLbl15 = new javax.swing.JLabel();
        PercntageLbl16 = new javax.swing.JLabel();
        PercntageLbl17 = new javax.swing.JLabel();
        PercntageLbl18 = new javax.swing.JLabel();
        PercntageLbl19 = new javax.swing.JLabel();
        PercntageLbl20 = new javax.swing.JLabel();
        PercntageLbl21 = new javax.swing.JLabel();
        PercntageLbl22 = new javax.swing.JLabel();
        PercntageLbl23 = new javax.swing.JLabel();
        PercntageLbl24 = new javax.swing.JLabel();
        PercntageLbl25 = new javax.swing.JLabel();
        PercntageLbl26 = new javax.swing.JLabel();
        PercntageLbl27 = new javax.swing.JLabel();
        VitaminATxtField = new javax.swing.JTextField();
        this.textFields.add(VitaminATxtField);
        VitaminB1TxtField = new javax.swing.JTextField();
        this.textFields.add(VitaminB1TxtField);
        VitaminB2TxtField = new javax.swing.JTextField();
        this.textFields.add(VitaminB2TxtField);
        VitaminB3TxtField = new javax.swing.JTextField();
        this.textFields.add(VitaminB3TxtField);
        VitaminB5TxtField = new javax.swing.JTextField();
        this.textFields.add(VitaminB5TxtField);
        VitaminB6TxtField = new javax.swing.JTextField();
        this.textFields.add(VitaminB6TxtField);
        VitaminB7TxtField = new javax.swing.JTextField();
        this.textFields.add(VitaminB7TxtField);
        VitaminB9TxtField = new javax.swing.JTextField();
        this.textFields.add(VitaminB9TxtField);
        VitaminB12TxtField = new javax.swing.JTextField();
        this.textFields.add(VitaminB12TxtField);
        VitaminCTxtField = new javax.swing.JTextField();
        this.textFields.add(VitaminCTxtField);
        VitaminDTxtField = new javax.swing.JTextField();
        this.textFields.add(VitaminDTxtField);
        VitaminETxtField = new javax.swing.JTextField();
        this.textFields.add(VitaminETxtField);
        VitaminKTxtField = new javax.swing.JTextField();
        this.textFields.add(VitaminKTxtField);
        MineralSodiumTxtField = new javax.swing.JTextField();
        this.textFields.add(MineralSodiumTxtField);
        MineralPotassiumTxtField = new javax.swing.JTextField();
        this.textFields.add(MineralPotassiumTxtField);
        MineralCalciumTxtField = new javax.swing.JTextField();
        this.textFields.add(MineralCalciumTxtField);
        MineralPhosphorusTxtField = new javax.swing.JTextField();
        this.textFields.add(MineralPhosphorusTxtField);
        MineralMagnesiumTxtField = new javax.swing.JTextField();
        this.textFields.add(MineralMagnesiumTxtField);
        MineralSulfurTxtField = new javax.swing.JTextField();
        this.textFields.add(MineralSulfurTxtField);
        MineralIronTxtField = new javax.swing.JTextField();
        this.textFields.add(MineralIronTxtField);
        MineralChromiumTxtField = new javax.swing.JTextField();
        this.textFields.add(MineralChromiumTxtField);
        MineralCoboltTxtField = new javax.swing.JTextField();
        this.textFields.add(MineralCoboltTxtField);
        MineralCopperTxtField = new javax.swing.JTextField();
        this.textFields.add(MineralCopperTxtField);
        MineralZincTxtField = new javax.swing.JTextField();
        this.textFields.add(MineralZincTxtField);
        MineralManganeseTxtField = new javax.swing.JTextField();
        this.textFields.add(MineralManganeseTxtField);
        MineralMolybdenumTxtField = new javax.swing.JTextField();
        this.textFields.add(MineralMolybdenumTxtField);
        MineralIodineTxtField = new javax.swing.JTextField();
        this.textFields.add(MineralIodineTxtField);
        MineralSeleniumTxtField = new javax.swing.JTextField();
        this.textFields.add(MineralSeleniumTxtField);
        MineralFluorideTxtField = new javax.swing.JTextField();
        this.textFields.add(MineralFluorideTxtField);
        AddItemToRecordBtn = new javax.swing.JButton();

        jLabel14.setText("Vitamin B7(Biotin)");

        jLabel18.setText("Vitamin C");

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("%");

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("%");

        setBackground(new java.awt.Color(15, 93, 70));
        setPreferredSize(new java.awt.Dimension(790, 790));

        backBtn.setBackground(new java.awt.Color(0, 0, 0));
        backBtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("< Back");
        backBtn.setActionCommand("");
        backBtn.setBorder(null);
        backBtn.setBorderPainted(false);
        backBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        AddItemToRecordTitleLbl.setBackground(new java.awt.Color(0, 0, 0));
        AddItemToRecordTitleLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AddItemToRecordTitleLbl.setForeground(new java.awt.Color(255, 255, 255));
        AddItemToRecordTitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddItemToRecordTitleLbl.setText("Add Item To Record");
        AddItemToRecordTitleLbl.setOpaque(true);

        MRAP.setBackground(new java.awt.Color(102, 102, 102));
        MRAP.setOpaque(false);
        MRAP.setPreferredSize(new java.awt.Dimension(790, 790));
        MRAP.setLayout(null);

        SelectRecordToAddToLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SelectRecordToAddToLbl.setForeground(new java.awt.Color(255, 255, 255));
        SelectRecordToAddToLbl.setText("Select Record to Add to");
        MRAP.add(SelectRecordToAddToLbl);
        SelectRecordToAddToLbl.setBounds(6, 6, 296, 20);

        SelectRecordComboBox.setForeground(new java.awt.Color(0, 0, 0));
        SelectRecordComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food", "Drink" }));
        SelectRecordComboBox.setBorder(null);
        SelectRecordComboBox.setName("type"); // NOI18N
        MRAP.add(SelectRecordComboBox);
        SelectRecordComboBox.setBounds(6, 36, 175, 22);

        CaloriesLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CaloriesLbl.setForeground(new java.awt.Color(255, 255, 255));
        CaloriesLbl.setText("Calories");
        MRAP.add(CaloriesLbl);
        CaloriesLbl.setBounds(6, 64, 100, 20);

        TotalFatTxtField.setForeground(new java.awt.Color(0, 0, 0));
        TotalFatTxtField.setBorder(null);
        TotalFatTxtField.setName("Total Fat"); // NOI18N
        MRAP.add(TotalFatTxtField);
        TotalFatTxtField.setBounds(312, 72, 64, 16);

        ItemNamePnl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ItemNamePnl.setForeground(new java.awt.Color(255, 255, 255));
        ItemNamePnl.setText("Item Name");
        MRAP.add(ItemNamePnl);
        ItemNamePnl.setBounds(308, 6, 296, 20);

        ItemNameTxtField.setForeground(new java.awt.Color(0, 0, 0));
        ItemNameTxtField.setBorder(null);
        ItemNameTxtField.setName("foodName"); // NOI18N
        MRAP.add(ItemNameTxtField);
        ItemNameTxtField.setBounds(308, 36, 296, 16);

        VitaminsLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        VitaminsLbl.setForeground(new java.awt.Color(255, 255, 255));
        VitaminsLbl.setText("Vitamins");
        MRAP.add(VitaminsLbl);
        VitaminsLbl.setBounds(6, 232, 296, 20);

        MineralsLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MineralsLbl.setForeground(new java.awt.Color(255, 255, 255));
        MineralsLbl.setText("Minerals");
        MRAP.add(MineralsLbl);
        MineralsLbl.setBounds(308, 232, 296, 20);

        VitaminB1Lbl.setForeground(new java.awt.Color(255, 255, 255));
        VitaminB1Lbl.setText("Vitamin B1 (Thiamine)");
        VitaminB1Lbl.setName("Vitamin B1 (Thiamine)"); // NOI18N
        MRAP.add(VitaminB1Lbl);
        VitaminB1Lbl.setBounds(6, 280, 170, 16);

        VitaminALbl.setForeground(new java.awt.Color(255, 255, 255));
        VitaminALbl.setText("Vitamin A");
        MRAP.add(VitaminALbl);
        VitaminALbl.setBounds(6, 258, 52, 16);

        VitaminB2Lbl.setForeground(new java.awt.Color(255, 255, 255));
        VitaminB2Lbl.setText("Vitamin B2 (Riboflavin)");
        MRAP.add(VitaminB2Lbl);
        VitaminB2Lbl.setBounds(6, 302, 190, 16);

        VitaminB3Lbl.setForeground(new java.awt.Color(255, 255, 255));
        VitaminB3Lbl.setText("Vitamin B3 (Niacin)");
        MRAP.add(VitaminB3Lbl);
        VitaminB3Lbl.setBounds(6, 324, 180, 16);

        VitaminB5Lbl.setForeground(new java.awt.Color(255, 255, 255));
        VitaminB5Lbl.setText("Vitamin B5 (Pantothenic Acid)");
        MRAP.add(VitaminB5Lbl);
        VitaminB5Lbl.setBounds(6, 346, 190, 16);

        VitaminB6Lbl.setForeground(new java.awt.Color(255, 255, 255));
        VitaminB6Lbl.setText("Vitamin B6 (Pyridoxine)");
        MRAP.add(VitaminB6Lbl);
        VitaminB6Lbl.setBounds(6, 368, 190, 16);

        VitaminB7Lbl.setForeground(new java.awt.Color(255, 255, 255));
        VitaminB7Lbl.setText("Vitamin B7 (Biotin)");
        MRAP.add(VitaminB7Lbl);
        VitaminB7Lbl.setBounds(6, 390, 190, 16);

        VitaminB9Lbl.setForeground(new java.awt.Color(255, 255, 255));
        VitaminB9Lbl.setText("Vitamin B9 (Folate)");
        MRAP.add(VitaminB9Lbl);
        VitaminB9Lbl.setBounds(6, 412, 180, 16);

        VitaminB12Lbl.setForeground(new java.awt.Color(255, 255, 255));
        VitaminB12Lbl.setText("Vitamin B12 (Cobalamin)");
        MRAP.add(VitaminB12Lbl);
        VitaminB12Lbl.setBounds(6, 434, 190, 16);

        VitaminCLbl.setForeground(new java.awt.Color(255, 255, 255));
        VitaminCLbl.setText("Vitamin C");
        MRAP.add(VitaminCLbl);
        VitaminCLbl.setBounds(6, 456, 180, 16);

        VitaminDLbl.setForeground(new java.awt.Color(255, 255, 255));
        VitaminDLbl.setText("Vitamin D");
        MRAP.add(VitaminDLbl);
        VitaminDLbl.setBounds(6, 478, 180, 16);

        VitaminELbl.setForeground(new java.awt.Color(255, 255, 255));
        VitaminELbl.setText("Vitamin E");
        MRAP.add(VitaminELbl);
        VitaminELbl.setBounds(6, 500, 180, 16);

        VitaminKLbl.setForeground(new java.awt.Color(255, 255, 255));
        VitaminKLbl.setText("Vitamin K");
        MRAP.add(VitaminKLbl);
        VitaminKLbl.setBounds(6, 522, 190, 16);

        PercntageLbl1.setForeground(new java.awt.Color(255, 255, 255));
        PercntageLbl1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl1.setText("%");
        MRAP.add(PercntageLbl1);
        PercntageLbl1.setBounds(270, 258, 20, 16);

        PercntageLbl2.setForeground(new java.awt.Color(255, 255, 255));
        PercntageLbl2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl2.setText("%");
        MRAP.add(PercntageLbl2);
        PercntageLbl2.setBounds(270, 280, 20, 16);

        PercntageLbl3.setForeground(new java.awt.Color(255, 255, 255));
        PercntageLbl3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl3.setText("%");
        MRAP.add(PercntageLbl3);
        PercntageLbl3.setBounds(270, 302, 20, 16);

        PercntageLbl4.setForeground(new java.awt.Color(255, 255, 255));
        PercntageLbl4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl4.setText("%");
        MRAP.add(PercntageLbl4);
        PercntageLbl4.setBounds(270, 324, 20, 16);

        PercntageLbl5.setForeground(new java.awt.Color(255, 255, 255));
        PercntageLbl5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl5.setText("%");
        MRAP.add(PercntageLbl5);
        PercntageLbl5.setBounds(270, 346, 20, 16);

        PercntageLbl6.setForeground(new java.awt.Color(255, 255, 255));
        PercntageLbl6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl6.setText("%");
        MRAP.add(PercntageLbl6);
        PercntageLbl6.setBounds(270, 368, 20, 16);

        PercntageLbl7.setForeground(new java.awt.Color(255, 255, 255));
        PercntageLbl7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl7.setText("%");
        MRAP.add(PercntageLbl7);
        PercntageLbl7.setBounds(270, 390, 20, 16);

        PercntageLbl8.setForeground(new java.awt.Color(255, 255, 255));
        PercntageLbl8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl8.setText("%");
        MRAP.add(PercntageLbl8);
        PercntageLbl8.setBounds(270, 412, 20, 16);

        PercntageLbl9.setForeground(new java.awt.Color(255, 255, 255));
        PercntageLbl9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl9.setText("%");
        MRAP.add(PercntageLbl9);
        PercntageLbl9.setBounds(270, 434, 20, 16);

        PercntageLbl10.setForeground(new java.awt.Color(255, 255, 255));
        PercntageLbl10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl10.setText("%");
        MRAP.add(PercntageLbl10);
        PercntageLbl10.setBounds(270, 456, 20, 16);

        PercntageLbl11.setForeground(new java.awt.Color(255, 255, 255));
        PercntageLbl11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl11.setText("%");
        MRAP.add(PercntageLbl11);
        PercntageLbl11.setBounds(270, 478, 20, 16);

        PercntageLbl12.setForeground(new java.awt.Color(255, 255, 255));
        PercntageLbl12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl12.setText("%");
        MRAP.add(PercntageLbl12);
        PercntageLbl12.setBounds(270, 500, 20, 16);

        PercntageLbl13.setForeground(new java.awt.Color(255, 255, 255));
        PercntageLbl13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl13.setText("%");
        MRAP.add(PercntageLbl13);
        PercntageLbl13.setBounds(270, 522, 20, 16);

        ProteinLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ProteinLbl.setForeground(new java.awt.Color(255, 255, 255));
        ProteinLbl.setText("Protein");
        MRAP.add(ProteinLbl);
        ProteinLbl.setBounds(6, 168, 174, 20);

        ProteinTxtField.setForeground(new java.awt.Color(0, 0, 0));
        ProteinTxtField.setBorder(null);
        ProteinTxtField.setName("Protein"); // NOI18N
        MRAP.add(ProteinTxtField);
        ProteinTxtField.setBounds(6, 194, 100, 16);

        CholesterolLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CholesterolLbl.setForeground(new java.awt.Color(255, 255, 255));
        CholesterolLbl.setText("Cholesterol");
        MRAP.add(CholesterolLbl);
        CholesterolLbl.setBounds(6, 114, 174, 20);

        CholesterolTxtField.setForeground(new java.awt.Color(0, 0, 0));
        CholesterolTxtField.setBorder(null);
        CholesterolTxtField.setName("Cholesterol"); // NOI18N
        MRAP.add(CholesterolTxtField);
        CholesterolTxtField.setBounds(6, 140, 100, 16);

        SaturatedFatLbl.setForeground(new java.awt.Color(255, 255, 255));
        SaturatedFatLbl.setText("Saturated Fat");
        MRAP.add(SaturatedFatLbl);
        SaturatedFatLbl.setBounds(192, 103, 100, 16);

        TransFatLbl.setForeground(new java.awt.Color(255, 255, 255));
        TransFatLbl.setText("Trans Fat");
        TransFatLbl.setName("Trans Fat"); // NOI18N
        MRAP.add(TransFatLbl);
        TransFatLbl.setBounds(192, 131, 100, 16);

        CaloriesTxtField.setForeground(new java.awt.Color(0, 0, 0));
        CaloriesTxtField.setBorder(null);
        CaloriesTxtField.setName("Calories"); // NOI18N
        MRAP.add(CaloriesTxtField);
        CaloriesTxtField.setBounds(6, 90, 100, 16);

        TotalFatLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TotalFatLbl.setForeground(new java.awt.Color(255, 255, 255));
        TotalFatLbl.setText("Total Fat");
        TotalFatLbl.setName(""); // NOI18N
        MRAP.add(TotalFatLbl);
        TotalFatLbl.setBounds(192, 75, 100, 16);

        PolyunsaturatedFatLbl.setForeground(new java.awt.Color(255, 255, 255));
        PolyunsaturatedFatLbl.setText("Polyunsaturated");
        MRAP.add(PolyunsaturatedFatLbl);
        PolyunsaturatedFatLbl.setBounds(192, 159, 114, 16);

        MonounsaturatedFatLbl.setForeground(new java.awt.Color(255, 255, 255));
        MonounsaturatedFatLbl.setText("Monounsaturated");
        MRAP.add(MonounsaturatedFatLbl);
        MonounsaturatedFatLbl.setBounds(192, 187, 114, 16);

        SaturatedFatTxtField.setForeground(new java.awt.Color(0, 0, 0));
        SaturatedFatTxtField.setBorder(null);
        SaturatedFatTxtField.setName("Saturated Fat"); // NOI18N
        MRAP.add(SaturatedFatTxtField);
        SaturatedFatTxtField.setBounds(312, 100, 64, 16);

        TransFatTxtField.setForeground(new java.awt.Color(0, 0, 0));
        TransFatTxtField.setBorder(null);
        TransFatTxtField.setName("Trans Fat"); // NOI18N
        MRAP.add(TransFatTxtField);
        TransFatTxtField.setBounds(312, 128, 64, 16);

        PolyunsaturatedTxtField.setForeground(new java.awt.Color(0, 0, 0));
        PolyunsaturatedTxtField.setBorder(null);
        PolyunsaturatedTxtField.setName("Polyunsaturated Fat"); // NOI18N
        MRAP.add(PolyunsaturatedTxtField);
        PolyunsaturatedTxtField.setBounds(312, 156, 64, 16);

        MonounsaturatedTxtField.setForeground(new java.awt.Color(0, 0, 0));
        MonounsaturatedTxtField.setBorder(null);
        MonounsaturatedTxtField.setName("Monounsaturated Fat"); // NOI18N
        MRAP.add(MonounsaturatedTxtField);
        MonounsaturatedTxtField.setBounds(312, 184, 64, 16);

        TotalCarbohydrateLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TotalCarbohydrateLbl.setForeground(new java.awt.Color(255, 255, 255));
        TotalCarbohydrateLbl.setText("Total Carbohydrate");
        MRAP.add(TotalCarbohydrateLbl);
        TotalCarbohydrateLbl.setBounds(394, 79, 110, 16);

        DietaryFiberLbl.setForeground(new java.awt.Color(255, 255, 255));
        DietaryFiberLbl.setText("Dietary Fiber");
        MRAP.add(DietaryFiberLbl);
        DietaryFiberLbl.setBounds(394, 103, 110, 16);

        SugarsLbl.setForeground(new java.awt.Color(255, 255, 255));
        SugarsLbl.setText("Sugars");
        MRAP.add(SugarsLbl);
        SugarsLbl.setBounds(394, 131, 110, 16);

        AddedSugarsLbl.setForeground(new java.awt.Color(255, 255, 255));
        AddedSugarsLbl.setText("Added Sugars");
        MRAP.add(AddedSugarsLbl);
        AddedSugarsLbl.setBounds(394, 159, 110, 16);

        TotalCarbohydratesTxtField.setForeground(new java.awt.Color(0, 0, 0));
        TotalCarbohydratesTxtField.setBorder(null);
        TotalCarbohydratesTxtField.setName("Total Carbohydrate"); // NOI18N
        MRAP.add(TotalCarbohydratesTxtField);
        TotalCarbohydratesTxtField.setBounds(510, 76, 64, 16);

        DietaryFiberTxtField.setForeground(new java.awt.Color(0, 0, 0));
        DietaryFiberTxtField.setBorder(null);
        DietaryFiberTxtField.setName("Dietary Fiber"); // NOI18N
        MRAP.add(DietaryFiberTxtField);
        DietaryFiberTxtField.setBounds(510, 100, 64, 16);

        SugarsTxtField.setForeground(new java.awt.Color(0, 0, 0));
        SugarsTxtField.setToolTipText("");
        SugarsTxtField.setBorder(null);
        SugarsTxtField.setName("Sugars"); // NOI18N
        MRAP.add(SugarsTxtField);
        SugarsTxtField.setBounds(510, 128, 64, 16);

        AddedSugarsTxtField.setForeground(new java.awt.Color(0, 0, 0));
        AddedSugarsTxtField.setBorder(null);
        AddedSugarsTxtField.setName("Added Sugars"); // NOI18N
        MRAP.add(AddedSugarsTxtField);
        AddedSugarsTxtField.setBounds(510, 156, 64, 16);

        SodiumLbl.setForeground(new java.awt.Color(255, 255, 255));
        SodiumLbl.setText("Sodium");
        MRAP.add(SodiumLbl);
        SodiumLbl.setBounds(308, 258, 95, 16);

        PotassiumLbl.setForeground(new java.awt.Color(255, 255, 255));
        PotassiumLbl.setText("Potassium");
        MRAP.add(PotassiumLbl);
        PotassiumLbl.setBounds(308, 280, 95, 16);

        CalciumLbl.setForeground(new java.awt.Color(255, 255, 255));
        CalciumLbl.setText("Calcium");
        MRAP.add(CalciumLbl);
        CalciumLbl.setBounds(308, 302, 95, 16);

        PhosphorusLbl.setForeground(new java.awt.Color(255, 255, 255));
        PhosphorusLbl.setText("Phosphorus");
        PhosphorusLbl.setName(""); // NOI18N
        MRAP.add(PhosphorusLbl);
        PhosphorusLbl.setBounds(308, 324, 95, 16);

        MagnesiumLbl.setForeground(new java.awt.Color(255, 255, 255));
        MagnesiumLbl.setText("Magnesium");
        MRAP.add(MagnesiumLbl);
        MagnesiumLbl.setBounds(308, 346, 95, 16);

        SulfurLbl.setForeground(new java.awt.Color(255, 255, 255));
        SulfurLbl.setText("Sulfur");
        MRAP.add(SulfurLbl);
        SulfurLbl.setBounds(308, 368, 95, 16);

        IronLbl.setForeground(new java.awt.Color(255, 255, 255));
        IronLbl.setText("Iron");
        MRAP.add(IronLbl);
        IronLbl.setBounds(308, 390, 95, 16);

        ChromiumLbl.setForeground(new java.awt.Color(255, 255, 255));
        ChromiumLbl.setText("Chromium");
        MRAP.add(ChromiumLbl);
        ChromiumLbl.setBounds(308, 412, 95, 16);

        CoboltLbl.setForeground(new java.awt.Color(255, 255, 255));
        CoboltLbl.setText("Cobolt");
        MRAP.add(CoboltLbl);
        CoboltLbl.setBounds(308, 434, 95, 16);

        CopperLbl.setForeground(new java.awt.Color(255, 255, 255));
        CopperLbl.setText("Copper");
        MRAP.add(CopperLbl);
        CopperLbl.setBounds(308, 456, 95, 16);

        ZincLbl.setForeground(new java.awt.Color(255, 255, 255));
        ZincLbl.setText("Zinc");
        MRAP.add(ZincLbl);
        ZincLbl.setBounds(308, 478, 95, 16);

        ManganeseLbl.setForeground(new java.awt.Color(255, 255, 255));
        ManganeseLbl.setText("Manganese");
        ManganeseLbl.setToolTipText("");
        MRAP.add(ManganeseLbl);
        ManganeseLbl.setBounds(308, 500, 95, 16);

        MolybdenumLbl.setForeground(new java.awt.Color(255, 255, 255));
        MolybdenumLbl.setText("Molybdenum");
        MRAP.add(MolybdenumLbl);
        MolybdenumLbl.setBounds(308, 522, 95, 16);

        IodineLbl.setForeground(new java.awt.Color(255, 255, 255));
        IodineLbl.setText("Iodine");
        MRAP.add(IodineLbl);
        IodineLbl.setBounds(308, 544, 95, 16);

        SeleniumLbl.setForeground(new java.awt.Color(255, 255, 255));
        SeleniumLbl.setText("Selenium");
        MRAP.add(SeleniumLbl);
        SeleniumLbl.setBounds(308, 566, 95, 16);

        FluorideLbl.setForeground(new java.awt.Color(255, 255, 255));
        FluorideLbl.setText("Fluoride");
        MRAP.add(FluorideLbl);
        FluorideLbl.setBounds(308, 588, 95, 16);

        MgLbl1.setForeground(new java.awt.Color(255, 255, 255));
        MgLbl1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        MgLbl1.setText("mg");
        MRAP.add(MgLbl1);
        MgLbl1.setBounds(564, 258, 27, 16);

        MgLbl2.setForeground(new java.awt.Color(255, 255, 255));
        MgLbl2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        MgLbl2.setText("mg");
        MRAP.add(MgLbl2);
        MgLbl2.setBounds(564, 280, 27, 16);

        PercntageLbl14.setForeground(new java.awt.Color(255, 255, 255));
        PercntageLbl14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl14.setText("%");
        MRAP.add(PercntageLbl14);
        PercntageLbl14.setBounds(570, 302, 20, 16);

        PercntageLbl15.setForeground(new java.awt.Color(255, 255, 255));
        PercntageLbl15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl15.setText("%");
        MRAP.add(PercntageLbl15);
        PercntageLbl15.setBounds(570, 324, 20, 16);

        PercntageLbl16.setForeground(new java.awt.Color(255, 255, 255));
        PercntageLbl16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl16.setText("%");
        MRAP.add(PercntageLbl16);
        PercntageLbl16.setBounds(570, 346, 20, 16);

        PercntageLbl17.setForeground(new java.awt.Color(255, 255, 255));
        PercntageLbl17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl17.setText("%");
        MRAP.add(PercntageLbl17);
        PercntageLbl17.setBounds(570, 368, 20, 16);

        PercntageLbl18.setForeground(new java.awt.Color(255, 255, 255));
        PercntageLbl18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl18.setText("%");
        MRAP.add(PercntageLbl18);
        PercntageLbl18.setBounds(570, 390, 20, 16);

        PercntageLbl19.setForeground(new java.awt.Color(255, 255, 255));
        PercntageLbl19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl19.setText("%");
        MRAP.add(PercntageLbl19);
        PercntageLbl19.setBounds(570, 412, 20, 16);

        PercntageLbl20.setForeground(new java.awt.Color(255, 255, 255));
        PercntageLbl20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl20.setText("%");
        MRAP.add(PercntageLbl20);
        PercntageLbl20.setBounds(570, 434, 20, 16);

        PercntageLbl21.setForeground(new java.awt.Color(255, 255, 255));
        PercntageLbl21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl21.setText("%");
        MRAP.add(PercntageLbl21);
        PercntageLbl21.setBounds(570, 456, 20, 16);

        PercntageLbl22.setForeground(new java.awt.Color(255, 255, 255));
        PercntageLbl22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl22.setText("%");
        MRAP.add(PercntageLbl22);
        PercntageLbl22.setBounds(570, 478, 20, 16);

        PercntageLbl23.setForeground(new java.awt.Color(255, 255, 255));
        PercntageLbl23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl23.setText("%");
        MRAP.add(PercntageLbl23);
        PercntageLbl23.setBounds(570, 500, 20, 16);

        PercntageLbl24.setForeground(new java.awt.Color(255, 255, 255));
        PercntageLbl24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl24.setText("%");
        MRAP.add(PercntageLbl24);
        PercntageLbl24.setBounds(570, 522, 20, 16);

        PercntageLbl25.setForeground(new java.awt.Color(255, 255, 255));
        PercntageLbl25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl25.setText("%");
        MRAP.add(PercntageLbl25);
        PercntageLbl25.setBounds(570, 544, 20, 16);

        PercntageLbl26.setForeground(new java.awt.Color(255, 255, 255));
        PercntageLbl26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl26.setText("%");
        MRAP.add(PercntageLbl26);
        PercntageLbl26.setBounds(570, 566, 20, 16);

        PercntageLbl27.setForeground(new java.awt.Color(255, 255, 255));
        PercntageLbl27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PercntageLbl27.setText("%");
        MRAP.add(PercntageLbl27);
        PercntageLbl27.setBounds(570, 588, 20, 16);

        VitaminATxtField.setForeground(new java.awt.Color(0, 0, 0));
        VitaminATxtField.setBorder(null);
        VitaminATxtField.setName("Vitamin A"); // NOI18N
        MRAP.add(VitaminATxtField);
        VitaminATxtField.setBounds(200, 258, 64, 16);

        VitaminB1TxtField.setForeground(new java.awt.Color(0, 0, 0));
        VitaminB1TxtField.setBorder(null);
        VitaminB1TxtField.setName("Vitamin B1 (Thiamine)"); // NOI18N
        MRAP.add(VitaminB1TxtField);
        VitaminB1TxtField.setBounds(200, 280, 64, 16);

        VitaminB2TxtField.setForeground(new java.awt.Color(0, 0, 0));
        VitaminB2TxtField.setBorder(null);
        VitaminB2TxtField.setName("Vitamin B2 (Riboflavin)"); // NOI18N
        MRAP.add(VitaminB2TxtField);
        VitaminB2TxtField.setBounds(200, 302, 64, 16);

        VitaminB3TxtField.setForeground(new java.awt.Color(0, 0, 0));
        VitaminB3TxtField.setBorder(null);
        VitaminB3TxtField.setName("Vitamin B3 (Niacin)"); // NOI18N
        MRAP.add(VitaminB3TxtField);
        VitaminB3TxtField.setBounds(200, 324, 64, 16);

        VitaminB5TxtField.setForeground(new java.awt.Color(0, 0, 0));
        VitaminB5TxtField.setBorder(null);
        VitaminB5TxtField.setName("Vitamin B5 (Pantothenic Acid)"); // NOI18N
        MRAP.add(VitaminB5TxtField);
        VitaminB5TxtField.setBounds(200, 346, 64, 16);

        VitaminB6TxtField.setForeground(new java.awt.Color(0, 0, 0));
        VitaminB6TxtField.setBorder(null);
        VitaminB6TxtField.setName("Vitamin B6 (Pyridoxine)"); // NOI18N
        MRAP.add(VitaminB6TxtField);
        VitaminB6TxtField.setBounds(200, 368, 64, 16);

        VitaminB7TxtField.setForeground(new java.awt.Color(0, 0, 0));
        VitaminB7TxtField.setBorder(null);
        VitaminB7TxtField.setName("Vitamin B7 (Biotin)"); // NOI18N
        MRAP.add(VitaminB7TxtField);
        VitaminB7TxtField.setBounds(200, 390, 64, 16);

        VitaminB9TxtField.setForeground(new java.awt.Color(0, 0, 0));
        VitaminB9TxtField.setBorder(null);
        VitaminB9TxtField.setName("Vitamin B9 (Folate)"); // NOI18N
        MRAP.add(VitaminB9TxtField);
        VitaminB9TxtField.setBounds(200, 412, 64, 16);

        VitaminB12TxtField.setForeground(new java.awt.Color(0, 0, 0));
        VitaminB12TxtField.setBorder(null);
        VitaminB12TxtField.setName("Vitamin B12 (Cobalamin)"); // NOI18N
        MRAP.add(VitaminB12TxtField);
        VitaminB12TxtField.setBounds(200, 434, 64, 16);

        VitaminCTxtField.setForeground(new java.awt.Color(0, 0, 0));
        VitaminCTxtField.setBorder(null);
        VitaminCTxtField.setName("Vitamin C"); // NOI18N
        MRAP.add(VitaminCTxtField);
        VitaminCTxtField.setBounds(200, 456, 64, 16);

        VitaminDTxtField.setForeground(new java.awt.Color(0, 0, 0));
        VitaminDTxtField.setBorder(null);
        VitaminDTxtField.setName("Vitamin D"); // NOI18N
        MRAP.add(VitaminDTxtField);
        VitaminDTxtField.setBounds(200, 478, 64, 16);

        VitaminETxtField.setForeground(new java.awt.Color(0, 0, 0));
        VitaminETxtField.setBorder(null);
        VitaminETxtField.setName("Vitamin E"); // NOI18N
        MRAP.add(VitaminETxtField);
        VitaminETxtField.setBounds(200, 500, 64, 16);

        VitaminKTxtField.setForeground(new java.awt.Color(0, 0, 0));
        VitaminKTxtField.setBorder(null);
        VitaminKTxtField.setName("Vitamin K"); // NOI18N
        MRAP.add(VitaminKTxtField);
        VitaminKTxtField.setBounds(200, 522, 64, 16);

        MineralSodiumTxtField.setForeground(new java.awt.Color(0, 0, 0));
        MineralSodiumTxtField.setBorder(null);
        MineralSodiumTxtField.setName("Sodium"); // NOI18N
        MRAP.add(MineralSodiumTxtField);
        MineralSodiumTxtField.setBounds(500, 258, 64, 16);

        MineralPotassiumTxtField.setForeground(new java.awt.Color(0, 0, 0));
        MineralPotassiumTxtField.setBorder(null);
        MineralPotassiumTxtField.setName("Potassium"); // NOI18N
        MRAP.add(MineralPotassiumTxtField);
        MineralPotassiumTxtField.setBounds(500, 280, 64, 16);

        MineralCalciumTxtField.setForeground(new java.awt.Color(0, 0, 0));
        MineralCalciumTxtField.setBorder(null);
        MineralCalciumTxtField.setName("Calcium"); // NOI18N
        MRAP.add(MineralCalciumTxtField);
        MineralCalciumTxtField.setBounds(500, 302, 64, 16);

        MineralPhosphorusTxtField.setForeground(new java.awt.Color(0, 0, 0));
        MineralPhosphorusTxtField.setBorder(null);
        MineralPhosphorusTxtField.setName("Phosphorus"); // NOI18N
        MRAP.add(MineralPhosphorusTxtField);
        MineralPhosphorusTxtField.setBounds(500, 324, 64, 16);

        MineralMagnesiumTxtField.setForeground(new java.awt.Color(0, 0, 0));
        MineralMagnesiumTxtField.setBorder(null);
        MineralMagnesiumTxtField.setName("Magnesium"); // NOI18N
        MRAP.add(MineralMagnesiumTxtField);
        MineralMagnesiumTxtField.setBounds(500, 346, 64, 16);

        MineralSulfurTxtField.setForeground(new java.awt.Color(0, 0, 0));
        MineralSulfurTxtField.setBorder(null);
        MineralSulfurTxtField.setName("Sulfur"); // NOI18N
        MRAP.add(MineralSulfurTxtField);
        MineralSulfurTxtField.setBounds(500, 368, 64, 16);

        MineralIronTxtField.setForeground(new java.awt.Color(0, 0, 0));
        MineralIronTxtField.setBorder(null);
        MineralIronTxtField.setName("Iron"); // NOI18N
        MRAP.add(MineralIronTxtField);
        MineralIronTxtField.setBounds(500, 390, 64, 16);

        MineralChromiumTxtField.setForeground(new java.awt.Color(0, 0, 0));
        MineralChromiumTxtField.setBorder(null);
        MineralChromiumTxtField.setName("Chromium"); // NOI18N
        MRAP.add(MineralChromiumTxtField);
        MineralChromiumTxtField.setBounds(500, 412, 64, 16);

        MineralCoboltTxtField.setForeground(new java.awt.Color(0, 0, 0));
        MineralCoboltTxtField.setBorder(null);
        MineralCoboltTxtField.setName("Cobolt"); // NOI18N
        MRAP.add(MineralCoboltTxtField);
        MineralCoboltTxtField.setBounds(500, 434, 64, 16);

        MineralCopperTxtField.setForeground(new java.awt.Color(0, 0, 0));
        MineralCopperTxtField.setBorder(null);
        MineralCopperTxtField.setName("Copper"); // NOI18N
        MRAP.add(MineralCopperTxtField);
        MineralCopperTxtField.setBounds(500, 456, 64, 16);

        MineralZincTxtField.setForeground(new java.awt.Color(0, 0, 0));
        MineralZincTxtField.setBorder(null);
        MineralZincTxtField.setName("Zinc"); // NOI18N
        MRAP.add(MineralZincTxtField);
        MineralZincTxtField.setBounds(500, 478, 64, 16);

        MineralManganeseTxtField.setForeground(new java.awt.Color(0, 0, 0));
        MineralManganeseTxtField.setBorder(null);
        MineralManganeseTxtField.setName("Manganese"); // NOI18N
        MRAP.add(MineralManganeseTxtField);
        MineralManganeseTxtField.setBounds(500, 500, 64, 16);

        MineralMolybdenumTxtField.setForeground(new java.awt.Color(0, 0, 0));
        MineralMolybdenumTxtField.setBorder(null);
        MineralMolybdenumTxtField.setName("Molybdenum"); // NOI18N
        MRAP.add(MineralMolybdenumTxtField);
        MineralMolybdenumTxtField.setBounds(500, 522, 64, 16);

        MineralIodineTxtField.setForeground(new java.awt.Color(0, 0, 0));
        MineralIodineTxtField.setBorder(null);
        MineralIodineTxtField.setName("Iodine"); // NOI18N
        MRAP.add(MineralIodineTxtField);
        MineralIodineTxtField.setBounds(500, 544, 64, 16);

        MineralSeleniumTxtField.setForeground(new java.awt.Color(0, 0, 0));
        MineralSeleniumTxtField.setBorder(null);
        MineralSeleniumTxtField.setName("Selenium"); // NOI18N
        MRAP.add(MineralSeleniumTxtField);
        MineralSeleniumTxtField.setBounds(500, 566, 64, 16);

        MineralFluorideTxtField.setForeground(new java.awt.Color(0, 0, 0));
        MineralFluorideTxtField.setBorder(null);
        MineralFluorideTxtField.setName("Fluoride"); // NOI18N
        MRAP.add(MineralFluorideTxtField);
        MineralFluorideTxtField.setBounds(500, 588, 64, 16);

        AddItemToRecordBtn.setBackground(new java.awt.Color(10, 36, 2));
        AddItemToRecordBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddItemToRecordBtn.setText("Add Item To Record");
        AddItemToRecordBtn.setBorder(null);
        AddItemToRecordBtn.setBorderPainted(false);
        AddItemToRecordBtn.setFocusPainted(false);
        MRAP.add(AddItemToRecordBtn);
        AddItemToRecordBtn.setBounds(140, 630, 284, 38);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(MRAP, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(AddItemToRecordTitleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddItemToRecordTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(MRAP, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void addBackBtnListener(ActionListener a) {
        backBtn.addActionListener(a);
    }

    public void textFieldListener(ActionListener a) {
        for (JTextField f : textFields) {
            f.addActionListener(a);
        }
    }

    public void addTextFieldListener(ActionListener a) {
        for (JTextField txt : textFields) {
            txt.addActionListener(a);
        }
    }

    public String getItemType() {
        return (String) SelectRecordComboBox.getSelectedItem();
    }

    public void addAddBtnListener(ActionListener a) {
        AddItemToRecordBtn.addActionListener(a);
    }

    public String getItemName() {
        return ItemNameTxtField.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddItemToRecordBtn;
    private javax.swing.JLabel AddItemToRecordTitleLbl;
    private javax.swing.JLabel AddedSugarsLbl;
    private javax.swing.JTextField AddedSugarsTxtField;
    private javax.swing.JLabel CalciumLbl;
    private javax.swing.JLabel CaloriesLbl;
    private javax.swing.JTextField CaloriesTxtField;
    private javax.swing.JLabel CholesterolLbl;
    private javax.swing.JTextField CholesterolTxtField;
    private javax.swing.JLabel ChromiumLbl;
    private javax.swing.JLabel CoboltLbl;
    private javax.swing.JLabel CopperLbl;
    private javax.swing.JLabel DietaryFiberLbl;
    private javax.swing.JTextField DietaryFiberTxtField;
    private javax.swing.JLabel FluorideLbl;
    private javax.swing.JLabel IodineLbl;
    private javax.swing.JLabel IronLbl;
    private javax.swing.JLabel ItemNamePnl;
    private javax.swing.JTextField ItemNameTxtField;
    private javax.swing.JPanel MRAP;
    private javax.swing.JLabel MagnesiumLbl;
    private javax.swing.JLabel ManganeseLbl;
    private javax.swing.JLabel MgLbl1;
    private javax.swing.JLabel MgLbl2;
    private javax.swing.JTextField MineralCalciumTxtField;
    private javax.swing.JTextField MineralChromiumTxtField;
    private javax.swing.JTextField MineralCoboltTxtField;
    private javax.swing.JTextField MineralCopperTxtField;
    private javax.swing.JTextField MineralFluorideTxtField;
    private javax.swing.JTextField MineralIodineTxtField;
    private javax.swing.JTextField MineralIronTxtField;
    private javax.swing.JTextField MineralMagnesiumTxtField;
    private javax.swing.JTextField MineralManganeseTxtField;
    private javax.swing.JTextField MineralMolybdenumTxtField;
    private javax.swing.JTextField MineralPhosphorusTxtField;
    private javax.swing.JTextField MineralPotassiumTxtField;
    private javax.swing.JTextField MineralSeleniumTxtField;
    private javax.swing.JTextField MineralSodiumTxtField;
    private javax.swing.JTextField MineralSulfurTxtField;
    private javax.swing.JTextField MineralZincTxtField;
    private javax.swing.JLabel MineralsLbl;
    private javax.swing.JLabel MolybdenumLbl;
    private javax.swing.JLabel MonounsaturatedFatLbl;
    private javax.swing.JTextField MonounsaturatedTxtField;
    private javax.swing.JLabel PercntageLbl1;
    private javax.swing.JLabel PercntageLbl10;
    private javax.swing.JLabel PercntageLbl11;
    private javax.swing.JLabel PercntageLbl12;
    private javax.swing.JLabel PercntageLbl13;
    private javax.swing.JLabel PercntageLbl14;
    private javax.swing.JLabel PercntageLbl15;
    private javax.swing.JLabel PercntageLbl16;
    private javax.swing.JLabel PercntageLbl17;
    private javax.swing.JLabel PercntageLbl18;
    private javax.swing.JLabel PercntageLbl19;
    private javax.swing.JLabel PercntageLbl2;
    private javax.swing.JLabel PercntageLbl20;
    private javax.swing.JLabel PercntageLbl21;
    private javax.swing.JLabel PercntageLbl22;
    private javax.swing.JLabel PercntageLbl23;
    private javax.swing.JLabel PercntageLbl24;
    private javax.swing.JLabel PercntageLbl25;
    private javax.swing.JLabel PercntageLbl26;
    private javax.swing.JLabel PercntageLbl27;
    private javax.swing.JLabel PercntageLbl3;
    private javax.swing.JLabel PercntageLbl4;
    private javax.swing.JLabel PercntageLbl5;
    private javax.swing.JLabel PercntageLbl6;
    private javax.swing.JLabel PercntageLbl7;
    private javax.swing.JLabel PercntageLbl8;
    private javax.swing.JLabel PercntageLbl9;
    private javax.swing.JLabel PhosphorusLbl;
    private javax.swing.JLabel PolyunsaturatedFatLbl;
    private javax.swing.JTextField PolyunsaturatedTxtField;
    private javax.swing.JLabel PotassiumLbl;
    private javax.swing.JLabel ProteinLbl;
    private javax.swing.JTextField ProteinTxtField;
    private javax.swing.JLabel SaturatedFatLbl;
    private javax.swing.JTextField SaturatedFatTxtField;
    private javax.swing.JComboBox<String> SelectRecordComboBox;
    private javax.swing.JLabel SelectRecordToAddToLbl;
    private javax.swing.JLabel SeleniumLbl;
    private javax.swing.JLabel SodiumLbl;
    private javax.swing.JLabel SugarsLbl;
    private javax.swing.JTextField SugarsTxtField;
    private javax.swing.JLabel SulfurLbl;
    private javax.swing.JLabel TotalCarbohydrateLbl;
    private javax.swing.JTextField TotalCarbohydratesTxtField;
    private javax.swing.JLabel TotalFatLbl;
    private javax.swing.JTextField TotalFatTxtField;
    private javax.swing.JLabel TransFatLbl;
    private javax.swing.JTextField TransFatTxtField;
    private javax.swing.JLabel VitaminALbl;
    private javax.swing.JTextField VitaminATxtField;
    private javax.swing.JLabel VitaminB12Lbl;
    private javax.swing.JTextField VitaminB12TxtField;
    private javax.swing.JLabel VitaminB1Lbl;
    private javax.swing.JTextField VitaminB1TxtField;
    private javax.swing.JLabel VitaminB2Lbl;
    private javax.swing.JTextField VitaminB2TxtField;
    private javax.swing.JLabel VitaminB3Lbl;
    private javax.swing.JTextField VitaminB3TxtField;
    private javax.swing.JLabel VitaminB5Lbl;
    private javax.swing.JTextField VitaminB5TxtField;
    private javax.swing.JLabel VitaminB6Lbl;
    private javax.swing.JTextField VitaminB6TxtField;
    private javax.swing.JLabel VitaminB7Lbl;
    private javax.swing.JTextField VitaminB7TxtField;
    private javax.swing.JLabel VitaminB9Lbl;
    private javax.swing.JTextField VitaminB9TxtField;
    private javax.swing.JLabel VitaminCLbl;
    private javax.swing.JTextField VitaminCTxtField;
    private javax.swing.JLabel VitaminDLbl;
    private javax.swing.JTextField VitaminDTxtField;
    private javax.swing.JLabel VitaminELbl;
    private javax.swing.JTextField VitaminETxtField;
    private javax.swing.JLabel VitaminKLbl;
    private javax.swing.JTextField VitaminKTxtField;
    private javax.swing.JLabel VitaminsLbl;
    private javax.swing.JLabel ZincLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel33;
    // End of variables declaration//GEN-END:variables
}
