package nutrii.application.gui;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import nutrii.application.other.HibernateUtil;
import org.hibernate.Hibernate;

/**
 * Creates new form NutriiGUI
 *
 * @author Ellaira
 */
public class NutriiGUI extends javax.swing.JFrame {

    private MenuPanel menu;
    private MngRecordAddPnl addPanel;
    private MngRecordRemovePnl removePanel;
    private CreateMeal cm;
    private ViewMeals vm;
    
    private int xMouse;
    private int yMouse;

    public NutriiGUI() {
        initComponents();
        menu = new MenuPanel();
        addPanel = new MngRecordAddPnl();
        removePanel = new MngRecordRemovePnl();
        cm = new CreateMeal();
        vm = new ViewMeals();
        this.add(menu);
        menu.setVisible(true);
    }

    public ViewMeals getVm() {
        return vm;
    }

    public CreateMeal getCm() {
        return cm;
    }

    public MngRecordAddPnl getAddPanel() {
        return addPanel;
    }

    public MngRecordRemovePnl getRemovePanel() {
        return removePanel;
    }

    public MenuPanel getMenuPanel() {
        return menu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 620));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(790, 790));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
