/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nutrii.application.gui;

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author Blakey
 */
public class NutriiLoginGUI extends javax.swing.JFrame {

    int xMouse;
    int yMouse;

    public NutriiLoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EnterUsernameLbl = new javax.swing.JLabel();
        EnterPasswordLbl = new javax.swing.JLabel();
        usernameTxtField = new javax.swing.JTextField();

        passwordField = new javax.swing.JPasswordField();
        LoginBtn = new javax.swing.JToggleButton();
        CreateAccountBtn = new javax.swing.JToggleButton();
        closeBtn = new javax.swing.JButton();
        closeBtn.setOpaque(false);
        closeBtn.setContentAreaFilled(false);
        closeBtn.setBorderPainted(false);
        minBtn = new javax.swing.JButton();
        minBtn.setOpaque(false);
        minBtn.setContentAreaFilled(false);
        minBtn.setBorderPainted(false);
        bg = new javax.swing.JLabel();
        header = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nutrii");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(350, 380));
        setResizable(false);
        setSize(getPreferredSize());
        getContentPane().setLayout(null);

        EnterUsernameLbl.setForeground(new java.awt.Color(243, 243, 243));
        EnterUsernameLbl.setText("Enter Username:");
        getContentPane().add(EnterUsernameLbl);
        EnterUsernameLbl.setBounds(6, 115, 338, 16);

        EnterPasswordLbl.setForeground(new java.awt.Color(243, 243, 243));
        EnterPasswordLbl.setText("Enter Password:");
        getContentPane().add(EnterPasswordLbl);
        EnterPasswordLbl.setBounds(6, 185, 338, 16);

        usernameTxtField.setBackground(new java.awt.Color(10, 36, 2));
        usernameTxtField.setForeground(new java.awt.Color(204, 204, 204));
        usernameTxtField.setText("username");
        usernameTxtField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(usernameTxtField);
        usernameTxtField.setBounds(6, 137, 338, 30);

        passwordField.setBackground(new java.awt.Color(10, 36, 2));
        passwordField.setForeground(new java.awt.Color(204, 204, 204));
        passwordField.setText("jPasswordField1");
        passwordField.setBorder(null);
        getContentPane().add(passwordField);
        passwordField.setBounds(6, 210, 338, 30);

        LoginBtn.setBackground(new java.awt.Color(10, 36, 2));
        LoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        LoginBtn.setText("Login");
        LoginBtn.setBorder(null);
        LoginBtn.setFocusPainted(false);
        LoginBtn.setFocusable(false);
        LoginBtn.setRequestFocusEnabled(false);
        getContentPane().add(LoginBtn);
        LoginBtn.setBounds(6, 276, 132, 34);

        CreateAccountBtn.setBackground(new java.awt.Color(10, 36, 2));
        CreateAccountBtn.setForeground(new java.awt.Color(255, 255, 255));
        CreateAccountBtn.setText("Create Account");
        CreateAccountBtn.setBorder(null);
        CreateAccountBtn.setRequestFocusEnabled(false);
        CreateAccountBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CreateAccountBtnMousePressed(evt);
            }
        });
        getContentPane().add(CreateAccountBtn);
        CreateAccountBtn.setBounds(6, 322, 132, 34);

        closeBtn.setBackground(new java.awt.Color(96, 101, 104));
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(closeBtn);
        closeBtn.setBounds(310, 0, 40, 40);

        minBtn.setBorder(null);
        minBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minBtnActionPerformed(evt);
            }
        });
        getContentPane().add(minBtn);
        minBtn.setBounds(270, 0, 40, 40);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nutrii/application/gui/images/login2.jpg"))); // NOI18N
        bg.setText("jLabel1");
        getContentPane().add(bg);
        bg.setBounds(0, 0, 350, 380);

        header.setText("jLabel2");
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        getContentPane().add(header);
        header.setBounds(0, 0, 350, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_closeBtnActionPerformed

    private void minBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minBtnActionPerformed
        // TODO add your handling code here:
        this.setState(NutriiLoginGUI.ICONIFIED);
    }//GEN-LAST:event_minBtnActionPerformed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    public String getUserName() {
        return usernameTxtField.getText();
    }

    public char[] getPassword() {
        return passwordField.getPassword();
    }

    public void clearUserInput() {
        usernameTxtField.setText("");
    }

    public void clearPasswodInput() {
        passwordField.setText("");
    }

    /**
     * prevents the frame from "snapping" to the tip of the cursor which may
     * annoy the user
     *
     * @param evt
     */

//    public NutriiLoginGUI(int xMouse, int yMouse, JToggleButton CreateAccountBtn, JLabel EnterPasswordLbl, JLabel EnterUsernameLbl, JToggleButton LoginBtn, JLabel LoginOrSignUpTitleLbl, JLabel bg, JButton closeBtn, JLabel header, JButton minBtn, JPasswordField passwordField, JTextField usernameTxtField) throws HeadlessException {
//        this.xMouse = xMouse;
//        this.yMouse = yMouse;
//        this.CreateAccountBtn = CreateAccountBtn;
//        this.EnterPasswordLbl = EnterPasswordLbl;
//        this.EnterUsernameLbl = EnterUsernameLbl;
//        this.LoginBtn = LoginBtn;
//        this.LoginOrSignUpTitleLbl = LoginOrSignUpTitleLbl;
//        this.bg = bg;
//        this.closeBtn = closeBtn;
//        this.header = header;
//        this.minBtn = minBtn;
//        this.passwordField = passwordField;
//        this.usernameTxtField = usernameTxtField;
//    }

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void CreateAccountBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateAccountBtnMousePressed
        CreateAccountFrame caFrame = new CreateAccountFrame();
        caFrame.setVisible(true);
    }//GEN-LAST:event_CreateAccountBtnMousePressed

    public void addUserListener(ActionListener ual) {
        usernameTxtField.addActionListener(ual);
    }

    public void addPasswordListener(ActionListener pal) {
        passwordField.addActionListener(pal);
    }

    public void addLogInListener(ActionListener lia) {
        LoginBtn.addActionListener(lia);
    }

    public void addCreateBtnListener(ActionListener cre) {
        CreateAccountBtn.addActionListener(cre);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton CreateAccountBtn;
    private javax.swing.JLabel EnterPasswordLbl;
    private javax.swing.JLabel EnterUsernameLbl;
    private javax.swing.JToggleButton LoginBtn;
    private javax.swing.JLabel bg;
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel header;
    private javax.swing.JButton minBtn;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField usernameTxtField;
    // End of variables declaration//GEN-END:variables

}
