package nutrii.application.gui;

import nutrii.application.other.HibernateUtil;
import org.hibernate.Hibernate;

/**
 * Creates new form NutriiGUI
 * @author Ellaira
 */
public class NutriiGUI extends javax.swing.JFrame {
    
    private MenuPanel menu;
    
    public NutriiGUI() {
        initComponents();
        menu = new MenuPanel();
        
        this.add(menu);
        menu.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 620));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(790, 790));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
