
package nutrii.application.gui;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JList;

/**
 *
 * @author Blakey
 */
public class ViewMeals extends javax.swing.JPanel {

/**
 * Creates new form MngDietPnl2
 */
public ViewMeals() {
    initComponents();
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        MDP2 = new javax.swing.JPanel();
        MDP2SelectDayLbl = new javax.swing.JLabel();
        MDP2ListOfConsumedLbl = new javax.swing.JLabel();
        mealSelect = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        foodList = new javax.swing.JList<>();

        setBackground(new java.awt.Color(15, 93, 70));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(70, 94));

        backBtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("< Back");
        backBtn.setBorder(null);
        backBtn.setContentAreaFilled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Meals");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.NORTH);

        MDP2.setBackground(new java.awt.Color(102, 102, 102));
        MDP2.setOpaque(false);

        MDP2SelectDayLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MDP2SelectDayLbl.setForeground(new java.awt.Color(255, 255, 255));
        MDP2SelectDayLbl.setText("Select Meal:");

        MDP2ListOfConsumedLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MDP2ListOfConsumedLbl.setForeground(new java.awt.Color(255, 255, 255));
        MDP2ListOfConsumedLbl.setText("List of Consumed Items:");

        mealSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealSelectActionPerformed(evt);
            }
        });

        foodList.setBorder(null);
        foodList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        foodList.setFixedCellHeight(30);
        jScrollPane1.setViewportView(foodList);

        javax.swing.GroupLayout MDP2Layout = new javax.swing.GroupLayout(MDP2);
        MDP2.setLayout(MDP2Layout);
        MDP2Layout.setHorizontalGroup(
            MDP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MDP2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MDP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MDP2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(MDP2Layout.createSequentialGroup()
                        .addComponent(mealSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(MDP2SelectDayLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
                    .addComponent(MDP2ListOfConsumedLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)))
        );
        MDP2Layout.setVerticalGroup(
            MDP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MDP2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(MDP2SelectDayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mealSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MDP2ListOfConsumedLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(MDP2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void mealSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealSelectActionPerformed

    }//GEN-LAST:event_mealSelectActionPerformed

    public JList<String> getFoodList() {
        return foodList;
    }

    public JComboBox<String> getMealSelect() {
        return mealSelect;
    }

    public void addBackBtnListener(ActionListener a){
        backBtn.addActionListener(a);
    }

    public void addMealSelectListener(ActionListener a){
        mealSelect.addActionListener(a);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MDP2;
    private javax.swing.JLabel MDP2ListOfConsumedLbl;
    private javax.swing.JLabel MDP2SelectDayLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JList<String> foodList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> mealSelect;
    // End of variables declaration//GEN-END:variables
}
